### ISSUE TITLE
Error when trying to run examples, "specified module could not be found"

### ISSUE THREAD

**Issue by mrgreene** [peterbraden/node-opencv#109]
I'm trying to use opencv for an AR.Drone 2.0 project. I've finally got everything installed and built (I think), but whenever I try to run any on the example files, for example face_detection.js, I get the following error:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.

C:\Dropbox\My Dropbox\ngreene\ar-drone\node_modules\opencv\build\Release\opencv.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dropbox\My Dropbox\ngreene\ar-drone\node_modules\opencv\lib\bindings.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I'm running Windows7 x64, node 0.10.24, opencv 2.4.8.

If anyone has any idea on how to resolve this issue, I would love to hear it.

Thanks.

**Comment by emujagic-devlogic** [comment]
This solution worked for me too (requiring module, but haven't checked functionality but I guess it will work).

**Comment by danschultzer** [comment]
Seems like @bengfarrell's solution work, but the bindings have also changed so probably an outdated issue now.
