### ISSUE TITLE
cant find module error

### ISSUE THREAD

**Issue by balachandra** [peterbraden/node-opencv#14]
Hi There,

 Im getting following error while trying to run Face.js example after installing the module using ' npm install opencv'

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module '../build/Release/opencv.node'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/bala/Desktop/node-opencv/peterbraden-node-opencv-f855b2a/lib/bindings.js:1:80)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

Any suggestions on what could be causing the error? appreciate your help very much.

Thank you,
bala.

**Comment by pacozaa** [comment]
I couldn't find build.sh file too.

**Comment by RENO216** [comment]
I couldn't find build.sh file too.

**Comment by haipz** [comment]
I couldn't find build.sh file too.

**Comment by jakkuthompson** [comment]
I couldn't find build.sh file too.
