### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by bodagetta** [peterbraden/node-opencv#189]
I'm running yosimite and 

when I run

```npm install opencv```

I get this error

```node.js:815
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3```

**Comment by danschultzer** [comment]
Do you still experience this issue? Considering this is an issue from 2014, I'll close it for now.
