### ISSUE TITLE
Sample application doesn't work with opencv 2.4.10

### ISSUE THREAD

**Issue by edi9999** [peterbraden/node-opencv#207]
My code is just:

```
cv=require('opencv')

cv.readImage("./out.png", function(err, im){
  im.detectObject(cv.FACE_CASCADE, {}, function(err, faces){
    for (var i=0;i<faces.length; i++){
      var x = faces[i]
      im.ellipse(x.x + x.width/2, x.y + x.height/2, x.width/2, x.height/2);
    }
    im.save('./out.jpg');
  });
})
```

and opencv 2.4.10 is correctly installed.

I get the following error:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libopencv_contrib.so.2.4: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (node_modules/opencv/lib/bindings.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Does node-opencv work only with version 2.3 ? In that case it would be good to tell it in the readme

**Comment by edi9999** [comment]
Solved by using apt get rather than building open CV from source

**Comment by peterbraden** [comment]
glad you got it to work.

**Comment by aesopwolf** [comment]
Similar error on Mac 10.10.2 with opencv installed via ```brew install homebrew/science/opencv```. If anyone has a solution for this please add a comment here, thanks! :)

```bash
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/user/Desktop/nodecvtest/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node, 1): Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /usr/local/lib/libopencv_highgui.2.4.dylib
  Reason: Incompatible library version: libopencv_highgui.2.4.dylib requires version 33.0.0 or later, but libpng16.16.dylib provides version 31.0.0
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/Desktop/nodecvtest/node_modules/opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
