### ISSUE TITLE
Problem Installation on OS X

### ISSUE THREAD

**Issue by alamcordeiro** [peterbraden/node-opencv#230]
Hello

I have installed the opencv 3.0 using brew(no require sudo) on MAC OS 10.10
Works perfectly with python 
Running ```npm install opencv```

```
1276 error Darwin 14.1.0
1277 error argv "node" "/usr/local/bin/npm" "install" "opencv"
1278 error node v0.12.0
1279 error npm  v2.5.1
1280 error code ELIFECYCLE
1281 error opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
1281 error Exit status 1
1282 error Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
1282 error This is most likely a problem with the opencv package,
1282 error not with npm itself.
1282 error Tell the author that this fails on your system:
1282 error     node-pre-gyp install --fallback-to-build
1282 error You can get their info via:
1282 error     npm owner ls opencv
1282 error There is likely additional logging output above.
1283 verbose exit [ 1, true ]
```

Running  ``` node-pre-gyp install --fallback-to-build``` into node-opencv-master  repository clone folder:

```

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.3
node-pre-gyp info using node@0.12.0 | darwin | x64
node-pre-gyp info check checked for "/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" (not found)
node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz (falling back to source compile with node-gyp)
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | darwin | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Library/WebServer/Documents/node_modules/node-opencv-master/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alan/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/alan/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/Library/WebServer/Documents/node_modules/node-opencv-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
gyp: Call to 'pkg-config --cflags opencv' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64"
gyp ERR! cwd /Library/WebServer/Documents/node_modules/node-opencv-master
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --module_name=opencv --module_path=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:71:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Library/WebServer/Documents/node_modules/node-opencv-master
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --module_name=opencv --module_path=/Library/WebServer/Documents/node_modules/node-opencv-master/build/opencv/v3.0.0/Release/node-v14-darwin-x64' (1)

```

**Comment by Queuecumber** [comment]
When you say you installed "opencv 3.0" do you mean the opencv-node bindings v3.0.0 or do you mean the opencv c/c++ library version 3.0?

**Comment by alamcordeiro** [comment]
opencv c/c++ library version 3.0 :)

**Comment by Queuecumber** [comment]
Can you try with a 2.4.x version? Also do you have pkg-config installed I'm seeing an error related to that in your build

**Comment by alamcordeiro** [comment]
Yes, this error persist with opencv 2.4.10 libary

I'll check pkg-config now. Thanks

**Comment by alamcordeiro** [comment]
```Warning: pkg-config-0.28 already installed``` :/

**Comment by Queuecumber** [comment]
what does `pkg-config --cflags opencv` say

**Comment by alamcordeiro** [comment]
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found

**Comment by Queuecumber** [comment]
try adding `export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig` to your .bashrc and restart your terminal session (going off of http://stackoverflow.com/questions/8394678/compiling-a-basic-opencv-program-on-mac-os-x-10-7)

**Comment by alamcordeiro** [comment]
Yeah.
running  ```pkg-config --cflags opencv```
return: 
```-I/usr/local/Cellar/opencv/3.0.0-beta/include/opencv -I/usr/local/Cellar/opencv/3.0.0-beta/include ```

**Comment by Queuecumber** [comment]
Great retry your build

**Comment by alamcordeiro** [comment]
running npm install opencv
No errors yet. 
Installation in progress.
process node-pre-gyp and node-webkit using network :dancers:

**Comment by Queuecumber** [comment]
sooo all working then?

**Comment by alamcordeiro** [comment]
No :/

return this now

```

> opencv@3.0.0 install /Library/WebServer/Documents/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in
      namespace 'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace
      'cv'; did you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
2 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64" "--module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Library/WebServer/Documents/node_modules/opencv
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Library/WebServer/Documents/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Library/WebServer/Documents/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Library/WebServer/Documents/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "peterbraden/node-opencv"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Library/WebServer/Documents/cv/npm-debug.log


```

xcode already installed
Downloading xcode beta 6.3 beta now (~ 2.5GB)

**Comment by alamcordeiro** [comment]
No
now return this:

```
> opencv@3.0.0 install /Library/WebServer/Documents/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in
      namespace 'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace
      'cv'; did you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
2 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64" "--module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Library/WebServer/Documents/node_modules/opencv
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Library/WebServer/Documents/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Library/WebServer/Documents/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Library/WebServer/Documents/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Library/WebServer/Documents/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Library/WebServer/Documents/cv/npm-debug.log
```

**Comment by alamcordeiro** [comment]
Pty.js solved this error 15 days ago

https://github.com/chjj/pty.js/commit/8838e92bb7e553c9e9df038181296f60d52f374b

**Comment by Queuecumber** [comment]
I don't see what their issue has to do with this

You're still using the 2.4.x opencv right?

**Comment by Queuecumber** [comment]
Ok nvm I see the problem, you are using the 3.0.x libraries. The 3.0.x versions introduce many breaking changes that node-opencv hasn't addressed (and as far as I know there are no plans to). Get rid of opencv 3.0 from your computer and make sure you have 2.4 installed and try again

**Comment by alamcordeiro** [comment]
ok :)

**Comment by alamcordeiro** [comment]
Success installed :dancers: 
openCV library 2.4.10

Thank you very much 

i deleted some comments to help others with same problems.

**Comment by Queuecumber** [comment]
Great go ahead and close, good luck with your project

**Comment by Queuecumber** [comment]
@alamcordeiro Please close this issue it is resolved, @peterbraden  if he doesn't close this you can close it as well

**Comment by peterbraden** [comment]
Thanks, I'll close

**Comment by oIsCore** [comment]
Hi I am trying to install on Intel Galileo GEN 1 and this is what I get:


root@quark00a8ee:~# npm install opencv
npm http GET https://registry.npmjs.org/opencv
npm http 200 https://registry.npmjs.org/opencv
npm http GET https://registry.npmjs.org/opencv/-/opencv-3.0.0.tgz
npm http 200 https://registry.npmjs.org/opencv/-/opencv-3.0.0.tgz
npm http GET https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/buffers
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/buffers
npm http 200 https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.5.31.tgz
npm http GET https://registry.npmjs.org/nan/-/nan-1.4.3.tgz
npm http 200 https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz
npm http 200 https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.5.31.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.4.3.tgz

> opencv@3.0.0 install /home/root/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 status code downloading tarball (falling back to source compile with node-gyp)
make: Entering directory '/home/root/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  SOLINK_MODULE(target) Release/obj.target/opencv.node
/usr/lib/gcc/i586-poky-linux/4.8.2/../../../../i586-poky-linux/bin/ld: cannot find -lopencv_ts
collect2: error: ld returned 1 exit status
opencv.target.mk:148: recipe for target 'Release/obj.target/opencv.node' failed
make: *** [Release/obj.target/opencv.node] Error 1
make: Leaving directory '/home/root/node_modules/opencv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.8.7-yocto-standard
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32" "--module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v11-linux-ia32.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz"
gyp ERR! cwd /home/root/node_modules/opencv
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32 --module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/root/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:753:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
node-pre-gyp ERR! System Linux 3.8.7-yocto-standard
node-pre-gyp ERR! command "node" "/home/root/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/root/node_modules/opencv
node-pre-gyp ERR! node -v v0.10.28
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32 --module=/home/root/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-linux-ia32/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-linux-ia32.tar.gz' (1)
npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.0.0 install script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.7-yocto-standard
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "opencv"
npm ERR! cwd /home/root
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/root/npm-debug.log
npm ERR! not ok code 0
