### ISSUE TITLE
Bad OpenCV minor version?

### ISSUE THREAD

**Issue by mshalm** [peterbraden/node-opencv#231]
I have OpenCV 2.4.10 installed but running "npm install opencv" fails with the following message:

Error: libopencv_core.so.2.3: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3

Which to me makes me assume that the problem is that it is searching for opencv 2.3.x resources.
I'm on Ubuntu 14.04 LTS.

**Comment by Queuecumber** [comment]
@peterbraden I think your precompiled binaries only link against opencv 2.3, which is a problem because not everyone has the version. Not sure what the best fix is for that

**Comment by peterbraden** [comment]
can you try running 'npm install --build-from-source'?

**Comment by danschultzer** [comment]
Since this is more than a year old with no follow-up, I'll close it for now.
