### ISSUE TITLE
Update documentation with instructions on how to install on Windows

### ISSUE THREAD

**Issue by guywithcrookedface** [peterbraden/node-opencv#237]
I'm having some problems installing on Windows 7 (x64). I see that there are issues about the problem I'm seeing (pkg-config missing https://github.com/peterbraden/node-opencv/pull/188), but there is no clear solution that I can find. Can a developer or someone that has gotten this installed on Windows create a patch for the README.md that clearly states what steps need to be performed in order to get node-opencv installed on Windows 7 (x64)?

I'm a bit confused about the different discussions going on in the issues:

This one leads me to believe that everything should just work with npm install opencv:
* https://github.com/peterbraden/node-opencv/pull/188

This one says to install pkg-config?
* https://groups.google.com/d/msg/nodejs/u-FjTUVSh-w/LUP8mM706AsJ

This is the one that best explains what I'm seeing, and I can't figure out what the final solution is here:
* https://github.com/peterbraden/node-opencv/issues/83

**Comment by guywithcrookedface** [comment]
After a bunch of digging, I found this article (Chinese maybe?) that's going to take me some time to try. If it ends up working, I'll comment with the steps required to get it working.

http://ayapi.github.io/posts/node-opencvonwin8x64/

**Comment by guywithcrookedface** [comment]
Looks like one of the forks has a nice section about installing on Windows... I'm going to try that as well:

https://github.com/notcoffeetable/node-opencv#windows-setup

**Comment by guywithcrookedface** [comment]
Ahhh, got it compiled... I'll try some test code to confirm and then report back.

**Comment by guywithcrookedface** [comment]
Okay, it compiles, but I'm getting another error now when trying to run a simple test application:

```
C:\Users\user\projects\project>node test.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Users\user\projects\project\node_modules\opencv\build\opencv\v3.0.0\Release\node-v11-win32-x64\opencv.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\user\projects\project\node_modules\opencv\lib\bindings.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

The code I'm trying to run:

```
var cv = require('opencv');
```

**Comment by guywithcrookedface** [comment]
I'll open a new issue for the bug I'm seeing.
