### ISSUE TITLE
Specified module "opencv" not found on Windows 7 (x64)

### ISSUE THREAD

**Issue by guywithcrookedface** [peterbraden/node-opencv#238]
I managed to get an opencv.node file compiled and am now trying to run a simple application.

Test application:
```
var cv = require('opencv');
```

The resulting error I get is:
```
C:\Users\user\projects\project>node test.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Users\user\projects\project\node_modules\opencv\build\opencv\v3.0.0\Release\node-v11-win32-x64\opencv.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\user\projects\project\node_modules\opencv\lib\bindings.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I have confirmed that the file in question does exist by copying the path directly from the error message into the Windows explorer location bar:

```
C:\Users\user\projects\project\node_modules\opencv\build\opencv\v3.0.0\Release\node-v11-win32-x64\opencv.node
```

The versions I'm using are:
```
Node: v0.10.33
NPM: 1.4.28
OpenCV: 2.4.9
Visual Studio: 2013
OS: Windows 7 64-bit
```

**Comment by guywithcrookedface** [comment]
I wonder if it's because I compiled with 2.4.9 and opencv-node is expecting 2.4.4?

**Comment by guywithcrookedface** [comment]
@aahz Awesome man, nice find re. #109!
