### ISSUE TITLE
Install failed on Fedora 22

### ISSUE THREAD

**Issue by jchristi** [peterbraden/node-opencv#265]
```bash
$ sudo npm install -g opencv
npm WARN installMany node-pre-gyp was bundled with opencv@3.0.0, but bundled package wasn't found in unpacked tree

> opencv@3.0.0 install /usr/lib/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/2.3.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/opencv/.node-gyp"
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
gyp: Call to 'pkg-config --cflags "opencv >= 2.3.1"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.5-300.fc22.x86_64
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v44" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64" "--module=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v44-linux-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz"
gyp ERR! cwd /usr/lib/node_modules/opencv
gyp ERR! node -v v2.3.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/iojs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v44 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64 --module=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v44-linux-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.0.5-300.fc22.x86_64
node-pre-gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/opencv
node-pre-gyp ERR! node -v v2.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/iojs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v44 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64 --module=/usr/lib/node_modules/opencv/build/opencv/v3.0.0/Release/node-v44-linux-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v44-linux-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v44-linux-x64.tar.gz' (1)
npm ERR! Linux 4.0.5-300.fc22.x86_64
npm ERR! argv "/usr/bin/iojs" "/bin/npm" "install" "-g" "opencv"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.
```
[npm-debug.log](https://gist.github.com/jchristi/58edf04469ccb8ea7b6a).

**Comment by jchristi** [comment]
I have the opencv rpm installed. I tried installing opencv-devel rpm and I get a different error now:
```bash
make: Entering directory '/usr/lib/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/OpenCV.h:12:0,
                 from ../src/init.cc:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:207:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
In file included from ../src/OpenCV.h:4:0,
                 from ../src/init.cc:1:
/usr/lib/node_modules/opencv/.node-gyp/2.3.1/deps/v8/include/v8.h:4188:27: note: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/usr/lib/node_modules/opencv/.node-gyp/2.3.1/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
opencv.target.mk:103: recipe for target 'Release/obj.target/opencv/src/init.o' failed
make: *** [Release/obj.target/opencv/src/init.o] Error 1
```

**Comment by jchristi** [comment]
nodejs/io.js#456 Possibly an issue with dependencies?

**Comment by bruteche** [comment]
I've error to on linux mint : 

sudo npm install
npm WARN installMany node-pre-gyp was bundled with opencv@3.0.0, but bundled package wasn't found in unpacked tree

> opencv@3.0.0 install /home/bruno/SVN/gbot/eye/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/bruno/SVN/gbot/eye/node_modules/opencv/.node-gyp"
make: Entering directory '/home/bruno/SVN/gbot/eye/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:0:
../src/CascadeClassifierWrap.h:5:7: error: ‘CascadeClassifier’ in namespace ‘cv’ does not name a type
   cv::CascadeClassifier cc;
       ^
In file included from ../src/init.cc:6:0:
../src/VideoCaptureWrap.h:5:11: error: ‘VideoCapture’ in namespace ‘cv’ does not name a type
       cv::VideoCapture cap;
           ^
opencv.target.mk:104: recipe for target 'Release/obj.target/opencv/src/init.o' failed
make: *** [Release/obj.target/opencv/src/init.o] Error 1
make: Leaving directory '/home/bruno/SVN/gbot/eye/node_modules/opencv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-4-586
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/home/bruno/SVN/gbot/eye/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-linux-ia32" "--module=/home/bruno/SVN/gbot/eye/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-linux-ia32/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v14-linux-ia32.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-linux-ia32.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-linux-ia32.tar.gz"
