### ISSUE TITLE
Install failed on macosx

### ISSUE THREAD

**Issue by iahu** [peterbraden/node-opencv#266]
I have installed opencv.
I got a fail as i run `npm i opencv`.
pls help,thx!

```
npm WARN installMany node-pre-gyp was bundled with opencv@3.0.0, but bundled package wasn't found in unpacked tree

> opencv@3.0.0 install /Users/hub/source/cv/src/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in
      namespace 'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace
      'cv'; did you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
2 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64" "--module=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/hub/source/cv/src/node_modules/opencv
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/hub/source/cv/src/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/Users/hub/source/cv/src/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/hub/source/cv/src/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/Users/hub/source/cv/src/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "opencv"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hub/source/cv/src/npm-debug.log
```

**Comment by c4live** [comment]
Same here:
```
npm install --save opencv
/
> opencv@3.0.0 install xxxxxx/node_modules/opencv
> node-pre-gyp install --fallback-to-build

2015-07-09 16:34:12.637 xcodebuild[26392:179636] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in namespace 'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace 'cv'; did you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
2 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/xxx/.nvm/v0.10.31/bin/node" "/Users/xxx/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v11" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64" "--module=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v11-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz"
gyp ERR! cwd /Users/xxx/yyyy/node_modules/opencv
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/xxx/.nvm/v0.10.31/bin/node /Users/xxx/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64 --module=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/yyyy/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/Users/xxx/yyyy/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/xxx/yyyy/node_modules/opencv
node-pre-gyp ERR! node -v v0.10.31
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/Users/xxx/.nvm/v0.10.31/bin/node /Users/xxx/.nvm/v0.12.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v11 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64 --module=/Users/xxx/yyyy/node_modules/opencv/build/opencv/v3.0.0/Release/node-v11-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v11-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v11-darwin-x64.tar.gz' (1)
npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.4.0
npm ERR! command "/Users/xxx/.nvm/v0.10.31/bin/node" "/Users/xxx/.nvm/v0.10.31/bin/npm" "install" "--save" "opencv"
npm ERR! cwd /Users/xxx/yyyy
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xxx/yyyy/npm-debug.log
npm ERR! not ok code 0
```

**Comment by iahu** [comment]
1. opencv@3.0 has problem, opencv@2.4 is ok.  `brew install opencv`. config the opencv enverment value
2. make sure `pkg-config --cflags opencv` get a info look like this `-I/usr/local/Cellar/opencv/2.4.11_1/include/opencv -I/usr/local/Cellar/opencv/2.4.11_1/include `
3. install node-opencv form locally
4. install all dependencies of node-opencv
5. finally run `node-pre-gyp install --fallback-to-build` at `node_modules/opencv/`

**Comment by fotoKrille** [comment]
Can you do a more detail description? This is totally new for me... :(
-bash: node-pre-gyp: command not found

**Comment by davduran** [comment]
OK. I just make the whole process from 0...

/Mac Instructions/
1) Uninstall OpenCV 3.0
2) Install "brew"
3) In the terminal: brew install opencv
4) Go to node_modules in your project folder.
5) Download node_opencv_master
6) Unzip and rename the folder to "opencv"
7) Enter to "opencv" and make: npm install (some warnings on this step but don't worry)
8) Now you can exit to the root project. And throw a normal "npm install" (just npm install, without opencv).

Voilà! Now compiles and the examples works.

**Comment by teamhail** [comment]
I've been trying to get node-opencv working from the suggestions above, but from other research it seems only opencv 2.4.9-2.4.11 works?  Is that correct?  v2.4.12 and ^2.4.x are creating this error:

npm ERR! No compatible version found: opencv@^2.4.x
npm ERR! Valid install targets:
["3.2.0","3.1.0","3.0.0","2.0.0","1.0.0","0.7.0","0.6.0","0.5.0","0.4.0","0.3.1","0.3.0","0.2.0","0.1.0","0.0.12","0.0.11","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]

My npm is 3.3.8 and node is 4.2.1.  Thanks.

**Comment by iahu** [comment]
v2.4 is mean c version opencv

**Comment by kruny1001** [comment]
I have a same issue 
$pkg-config --cflags opencv
-I/opt/local/include/opencv -I/opt/local/include 

how can i fix it?

**Comment by SimplyY** [comment]
@kruny1001 if you use brew install opencv you should do follow ,else like this error info "package opencv not find"

 solution find in here http://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/

@davduran  your solution shuld add this step before 7. npm install 

my solution export PKG_CONFIG_PATH=/usr/local/Cellar/opencv/2.4.12_2/lib/pkgconfig/

**Comment by danschultzer** [comment]
Yeah, uninstalling opencv (however way it was installed), and installing it with brew should do the trick.
