### ISSUE TITLE
Opencv installed on windows. but npm get error.

### ISSUE THREAD

**Issue by hahamed** [peterbraden/node-opencv#268]
Hello,
I downloaded opencv 3.0.0 and extracted to c:\opencv.
I added environment variable to windows: Add OPENCV_DIR=C:\opencv\build\x86\vc12 and add Path ;%OPENCV_DIR%\bin.

when i execute npm install opencv -g, i get this error:
        child_process: customFds option is deprecated, use stdio instead.
        gyp: Call to 'pkg-config --cflags "opencv >= 2.4.9"' returned exit status -10737
        41515. while trying to load binding.gyp
        gyp ERR! configure error
        gyp ERR! stack Error: `gyp` failed with exit code: 1
        gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\Desktop\KM\n
        ode\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
        :12)

Any Help? thanks

**Comment by its2mc** [comment]
same issue.. no solution.. its like they totally do not work with windows.. I also had issues in linux.. I lost faith in node-opencv reverted to pyopencv.. more reliable.

**Comment by luchom** [comment]
Same issue here running:
windows 10
node 0.12.2
npm 2.7.4
openCV 3.0
python 3.5.0

**Comment by kikaendeavor** [comment]
@peterbraden, does there a solution to install opencv on windows system?

**Comment by danschultzer** [comment]
@kikaendeavor what error do you experience?

**Comment by cchamberlain** [comment]
This is what I get on Windows 10 / node 7.0.0 after following the instructions. Seems like having pre-built binaries would fix it. FWIW I have windows-build-tools installed:

```bash
C:\Users\cchamberlain\noderaider\node-opencv\examples [master ≡]> npm i -g opencv

> opencv@6.0.0 install C:\users\cchamberlain\local\npm\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)
Warning: Missing input files:
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\CamShift.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Contours.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\ImgProc.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Matrix.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\HighGUI.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Features2d.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/C:\Users\cchamberlain\npm\npm\node_modules\node-gyp\src\win_delay_load_hook.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\BackgroundSubtractor.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\VideoCaptureWrap.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\LDAWrap.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Point.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Constants.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Stereo.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\OpenCV.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\FaceRecognizer.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\CascadeClassifierWrap.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\test\nativemat.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Calib3D.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\src\init.cc
C:\users\cchamberlain\local\npm\node_modules\opencv\build/..\c\users\cchamberlain\local\npm\node_modules\opencv\binding.gyp
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Matrix.cc
': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\OpenCV.cc
': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\CascadeCl
assifierWrap.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Point.cc'
: No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\init.cc':
 No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
  Constants.cc
  Calib3D.cc
  ImgProc.cc
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Contours.
cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
  Stereo.cc
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\HighGUI.c
c': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\CamShift.
cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
  LDAWrap.cc
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\VideoCapt
ureWrap.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\FaceRecog
nizer.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Backgroun
dSubtractor.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Features2
d.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\ImgProc.c
c': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Constants
.cc': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\LDAWrap.c
c': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Stereo.cc
': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\c\users\cchamberlain\local\npm\node_modules\opencv\src\Calib3D.c
c': No such file or directory [C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\cchamberlain\npm\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cchamberlain\\npm\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\users\\cchamberlain\\local\\npm\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v51-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\users\\cchamberlain\\local\\npm\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v51-win32-x64"
gyp ERR! cwd C:\users\cchamberlain\local\npm\node_modules\opencv
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\cchamberlain\npm\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv\v6.0.0\Release\node-v51-win32-x64\opencv.node --module_name=opencv --module_path=C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv\v6.0.0\Release\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cchamberlain\local\npm\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cchamberlain\\local\\npm\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\users\cchamberlain\local\npm\node_modules\opencv
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\cchamberlain\npm\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv\v6.0.0\Release\node-v51-win32-x64\opencv.node --module_name=opencv --module_path=C:\users\cchamberlain\local\npm\node_modules\opencv\build\opencv\v6.0.0\Release\node-v51-win32-x64' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.31
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cchamberlain\\local\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "opencv"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cchamberlain\noderaider\node-opencv\examples\npm-debug.log
```
