### ISSUE TITLE
No method called ImageSimilarity

### ISSUE THREAD

**Issue by saru95** [peterbraden/node-opencv#272]
I get this error after running the dissimilarity example .
```
saru95:lib sarthakmunshi$ node comparison.js

/Users/sarthakmunshi/Desktop/Print/all-image/lib/comparison.js:9
    cv.ImageSimilarity(car1, car2, function (err, dissimilarity) {
       ^
TypeError: Object #<Object> has no method 'ImageSimilarity'
    at /Users/sarthakmunshi/Desktop/Print/all-image/lib/comparison.js:9:8
    at /Users/sarthakmunshi/Desktop/Print/all-image/lib/comparison.js:6:6
    at Object.<anonymous> (/Users/sarthakmunshi/Desktop/Print/all-image/lib/comparison.js:3:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by Queuecumber** [comment]
How are you compiling, which opencv version do you have?

see
https://github.com/peterbraden/node-opencv/blob/585790f06e5667e52c7add413748621c2592e2c7/src/init.cc#L37

**Comment by danschultzer** [comment]
You need OpenCV >= 2.4 installed.
