### ISSUE TITLE
opencv does not install on mac os yosemite 

### ISSUE THREAD

**Issue by ashirsat** [peterbraden/node-opencv#281]
I am getting errors when I am trying to install opencv using the following command
npm install opencv

The error is as follows

> opencv@3.1.0 install /Users/aniketshirsat/node_ARDrone/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in
      namespace 'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace
      'cv'; did you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:15:
../src/Stereo.h:8:5: error: no type named 'StereoBM' in namespace 'cv'; did you
      mean simply 'StereoBM'?
    cv::StereoBM stereo;
    ^~~~~~~~~~~~
    StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public node::ObjectWrap {
      ^
../src/Stereo.h:14:27: error: no member named 'StereoBM' in namespace 'cv'; did
      you mean simply 'StereoBM'?
    StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities ...
                          ^~~~~~~~~~~~
                          StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public node::ObjectWrap {
      ^
../src/Stereo.h:14:41: error: no member named 'BASIC_PRESET' in 'StereoBM'
    StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities ...
                              ~~~~~~~~~~^
../src/Stereo.h:21:5: error: no type named 'StereoSGBM' in namespace 'cv'; did
      you mean simply 'StereoSGBM'?
    cv::StereoSGBM stereo;
    ^~~~~~~~~~~~~~
    StereoSGBM
../src/Stereo.h:19:7: note: 'StereoSGBM' declared here
class StereoSGBM: public node::ObjectWrap {
      ^
6 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.1.0" "--major=3" "--minor=1" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64" "--module=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64/opencv.node" "--remote_path=./opencv/v3.1.0/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/aniketshirsat/node_ARDrone/node_modules/opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.1.0 --major=3 --minor=1 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64 --module=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.1.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aniketshirsat/node_ARDrone/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/Users/aniketshirsat/node_ARDrone/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/aniketshirsat/node_ARDrone/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.1.0 --major=3 --minor=1 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64 --module=/Users/aniketshirsat/node_ARDrone/node_modules/opencv/build/opencv/v3.1.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.1.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.1.0/Release/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.1.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.


Can anyone suggest a fix for this.

**Comment by alanguir** [comment]
I'm getting this same error with almost all the same stats (Darwin 14.3 instead of 14.4, npm 1.3.24 instead of 2.11.3)

**Comment by ashirsat** [comment]
were you able to use it with node-ardrone?

**Comment by alanguir** [comment]
No, haven't tried. I don't have an AR drone. Anything of use there that you saw to get this package working? I'm still stuck after also trying to build opencv 2.8 - even though it seemed to get further along in the build before blowing up with the lower version number. 

Maybe I'll try all the way back to 2.3 and see if it's just that the bindings are expecting a very specific version of opencv

**Comment by alanguir** [comment]
I backed my node version down to v.10.36 and I'm now getting a partial install. Partial command line output is: 
```bash
> opencv@3.2.0 install /Users/alan/github/vision/node_modules/opencv
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
  CXX(target) Release/obj.target/opencv/src/Features2d.o
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  CXX(target) Release/obj.target/opencv/src/Stereo.o
  SOLINK_MODULE(target) Release/opencv.node
clang: error: no such file or directory: 'OpenCL'
clang: error: no such file or directory: 'AppKit'
clang: error: no such file or directory: 'QuartzCore'
clang: error: no such file or directory: 'QTKit'
clang: error: no such file or directory: 'Cocoa'
make: *** [Release/opencv.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alan/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.4.0
```

Which means it looks like it's choking on finding some native os-x libraries

**Comment by ashirsat** [comment]
If you just want to install opencv without the node package then you can
simply download the package from opencv.org or
using home-brew
brew install opencv

**Comment by davduran** [comment]
OK. I just make the whole process from 0...

/Mac Instructions/
1) Uninstall OpenCV 3.0
2) Install "brew"
3) In the terminal: brew install opencv
4) Go to node_modules in your project folder.
5) Download node_opencv_master
6) Unzip and rename the folder to "opencv"
7) Enter to "opencv" and make: npm install (some warnings on this step but don't worry)
8) Now you can exit to the root project. And throw a normal "npm install" (just npm install, without opencv).

Voilà! Now compiles and the examples works.

**Comment by danschultzer** [comment]
@davduran's answer seems to be a good fix for this. Furthermore, doing `brew install opencv3` works well for me in yosemite and sierra.
