### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ecSpl01t** [peterbraden/node-opencv#325]
```
Linux version 3.13.0-40-generic (buildd@comet) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014

npm : 2.11.3
node: v0.12.7

# npm install opencv
|
> opencv@3.2.0 install */Install-OpenCV/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
gyp: Call to 'pkg-config --cflags "opencv >= 2.3.1"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.2.0" "--major=3" "--minor=2" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64" "--module=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64/opencv.node" "--remote_path=./opencv/v3.2.0/Release/" "--package_name=node-v14-linux-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz"
gyp ERR! cwd */Install-OpenCV/node_modules/opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64 --module=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64/opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (*/Install-OpenCV/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.13.0-40-generic
node-pre-gyp ERR! command "node" "*/Install-OpenCV/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd */Install-OpenCV/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64 --module=*/Install-OpenCV/node_modules/opencv/build/opencv/v3.2.0/Release/node-v14-linux-x64/opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v14-linux-x64.tar.gz' (1)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     */npm-debug.log
```

**Comment by mousetraps** [comment]
Have you installed OpenCV yet? If so, there's a blog post on how to resolve this very issue: http://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/

**Comment by nielsnl68** [comment]
Hello @mousetraps 
that blog post does not make any sense at all for me.
I have the same issue as above and tried to do as described but that did not helped at all.

**Comment by lschans** [comment]
Is there a solution? Or did anyone get it to work.
I have the same issue on OSX el Capitan, using node v4.1.0 using opencv 3 installed with brew.

The link offered by mousetrap didn't help for me.

**Comment by vivek1729** [comment]
@lschans , I have the exact same issue. Working with el Capitan and opencv 3 installed. Looking for a solution :)

**Comment by fredydeltoro** [comment]
i had the same trouble, i finish using nvm to change node version and work with v0.10.13, and works but very slowly, i work on ubuntu 14.04

**Comment by FliiFe** [comment]
I managed to compile it by deleting ~/.node-gyp .
Running 15.10.

**Comment by guatedude2** [comment]
Deleting ~/.node-gyp worked for me too

**Comment by emanuelef** [comment]
Same issue for me, I also tried to delete ~/.node-gyp but didn't help.

**Comment by danschultzer** [comment]
@ecSpl01t it seems like `libopencv-dev` [has not be installed](http://stackoverflow.com/a/21524027/939535). Can you try run `apt-get install libopencv-dev`? If it still doesn't work, try run `pkg-config --cflags opencv` and `pkg-config --libs opencv`.

@emanuelef what output do you get? Is it the `XX in namespace ‘cv’ does not name a type` or `No package 'opencv' found`.
