### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by FliiFe** [peterbraden/node-opencv#346]
Hey !
I can't manage to create the opencv var (`require('opencv')`).
I get this : 
```
Error: /home/fliife/node-opencv/build/opencv/v4.0.0/Release/node-v46-linux-x64/opencv.node: undefined symbol: _ZNK2cv9Algorithm5writeERNS_11FileStorageE
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/fliife/node-opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by FliiFe** [comment]
Oh, and btw, I'm using Ubuntu 15.10, node v4.2.2, npm 3.5.2, Opencv 2.3.

**Comment by danschultzer** [comment]
Try rebuild `node-opencv`:

```
$ rm -rf node_modules/
$ npm install
```

I'll close this for now, but reopen it if you still have any issues.

**Comment by lfreneda** [comment]
@FliiFe any progress on it? same problem here @w@

**Comment by lfreneda** [comment]
@FliiFe thanks anyway
