### ISSUE TITLE
cannot install with the latest version of node and npm

### ISSUE THREAD

**Issue by abedzantout** [peterbraden/node-opencv#357]
I have downgraded from opencv 3 to opencv2, and attempted to install node-opencv, 
however I get the following errors each time on my console:

```
Abeds-MacBook-Pro:ardrone-webflight AbedZantout$ sudo npm install opencv

> opencv@4.0.0 install /Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in namespace 'cv'; did you mean 'CascadeClassifierWrap'?
  cv::CascadeClassifier cc;
  ^~~~~~~~~~~~~~~~~~~~~
  CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public Nan::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:3: error: no type named 'VideoCapture' in namespace 'cv'; did you mean 'VideoCaptureWrap'?
  cv::VideoCapture cap;
  ^~~~~~~~~~~~~~~~
  VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public Nan::ObjectWrap {
      ^
In file included from ../src/init.cc:15:
../src/Stereo.h:8:3: error: no type named 'StereoBM' in namespace 'cv'; did you mean simply 'StereoBM'?
  cv::StereoBM stereo;
  ^~~~~~~~~~~~
  StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public Nan::ObjectWrap {
      ^
../src/Stereo.h:14:25: error: no member named 'StereoBM' in namespace 'cv'; did you mean simply 'StereoBM'?
  StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities = 0,
                        ^~~~~~~~~~~~
                        StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public Nan::ObjectWrap {
      ^
../src/Stereo.h:14:39: error: no member named 'BASIC_PRESET' in 'StereoBM'
  StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities = 0,
                            ~~~~~~~~~~^
../src/Stereo.h:23:3: error: no type named 'StereoSGBM' in namespace 'cv'; did you mean simply 'StereoSGBM'?
  cv::StereoSGBM stereo;
  ^~~~~~~~~~~~~~
  StereoSGBM
../src/Stereo.h:21:7: note: 'StereoSGBM' declared here
class StereoSGBM: public Nan::ObjectWrap {
      ^
6 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64"
gyp ERR! cwd /Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv
node-pre-gyp ERR! node -v v5.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/AbedZantout/Desktop/Node/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v47-darwin-x64' (1)
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AbedZantout/Desktop/Node/ardrone-webflight/npm-debug.log
```

**Comment by abedzantout** [comment]
I downgraded to node 0.12.7 and npm 2.11.3 after reading a couple of posts, but the problem persists:

```
Abeds-MacBook-Pro:ardrone-webflight AbedZantout$ npm install
|
> opencv@4.0.0 install /Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in namespace 'cv'; did you mean 'CascadeClassifierWrap'?
  cv::CascadeClassifier cc;
  ^~~~~~~~~~~~~~~~~~~~~
  CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public Nan::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:3: error: no type named 'VideoCapture' in namespace 'cv'; did you mean 'VideoCaptureWrap'?
  cv::VideoCapture cap;
  ^~~~~~~~~~~~~~~~
  VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public Nan::ObjectWrap {
      ^
In file included from ../src/init.cc:15:
../src/Stereo.h:8:3: error: no type named 'StereoBM' in namespace 'cv'; did you mean simply 'StereoBM'?
  cv::StereoBM stereo;
  ^~~~~~~~~~~~
  StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public Nan::ObjectWrap {
      ^
../src/Stereo.h:14:25: error: no member named 'StereoBM' in namespace 'cv'; did you mean simply 'StereoBM'?
  StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities = 0,
                        ^~~~~~~~~~~~
                        StereoBM
../src/Stereo.h:6:7: note: 'StereoBM' declared here
class StereoBM: public Nan::ObjectWrap {
      ^
../src/Stereo.h:14:39: error: no member named 'BASIC_PRESET' in 'StereoBM'
  StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities = 0,
                            ~~~~~~~~~~^
../src/Stereo.h:23:3: error: no type named 'StereoSGBM' in namespace 'cv'; did you mean simply 'StereoSGBM'?
  cv::StereoSGBM stereo;
  ^~~~~~~~~~~~~~
  StereoSGBM
../src/Stereo.h:21:7: note: 'StereoSGBM' declared here
class StereoSGBM: public Nan::ObjectWrap {
      ^
6 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/AbedZantout/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/AbedZantout/.nvm/versions/node/v0.12.7/bin/node" "/Users/AbedZantout/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64"
gyp ERR! cwd /Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/AbedZantout/.nvm/versions/node/v0.12.7/bin/node /Users/AbedZantout/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "node" "/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
Failed to execute '/Users/AbedZantout/.nvm/versions/node/v0.12.7/bin/node /Users/AbedZantout/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/AbedZantout/Desktop/ardrone-webflight/node_modules/opencv/build/opencv/v4.0.0/Release/node-v14-darwin-x64' (1)
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/AbedZantout/.nvm/versions/node/v0.12.7/bin/node" "/Users/AbedZantout/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AbedZantout/Desktop/ardrone-webflight/npm-debug.log
```

**Comment by bradrisse** [comment]
Try 

brew install gcc --force-bottle
brew tap homebrew/science
brew install opencv

**Comment by peterbraden** [comment]
Did this work?
