### ISSUE TITLE
3D reconstruction using 2D images

### ISSUE THREAD

**Issue by dvenkatsagar** [peterbraden/node-opencv#358]
Hello guys,

Im trying do a 3D reconstruction of Xray images, using this library, I just cant seem to find any example related to that (like for 2D images). Help is appreciated.

Thank you

**Comment by dvenkatsagar** [comment]
@peterbraden Ok i started experimenting with the library, now there is a problem where I am getting this error:

```bash
node: ../node_modules/nan/nan_object_wrap.h:55: void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>): Assertion `object->InternalFieldCount() > 0' failed.
```

Here is my current code(just converting the code from [stereo_match.py](https://github.com/Itseez/opencv/blob/master/samples/python/stereo_match.py))

```javascript
var cv = require('opencv');
var ply_header = 'ply'+
'format ascii 1.0'+
'element vertex %(vert_num)d'+
'property float x'+
'property float y'+
'property float z'+
'property uchar red'+
'property uchar green'+
'property uchar blue'+
'end_header';

console.log("Loading images ...");
cv.readImage('aloeL.jpg',function(err,imgL){
  cv.readImage('aloeR.jpg',function(err,imgR){
    imgL = imgL.pyrDown();
    imgR = imgR.pyrDown();
    var window_size = 3;
    var min_disp = 16;
    var num_disp = 112 - min_disp;
    var stereo = cv.StereoSGBM(min_disp,num_disp,3,Math.pow(8*3*window_size,2),Math.pow(32*3*window_size,2),1,10,100,2,0);
  });
});

```

When I run the code, it just gives that error. The problem is with the `cv.StereoSGBM()`. I even tried passing the arguments as an array and as an object. If I pass it as an array or object it gives me this error now : 

```bash
/home/sagar/Repositories/MS/Grad_Project/stereo_match.js:28
    var stereo = cv.StereoSGBM([min_disp,num_disp,3,Math.pow(8*3*window_size,2),Math.pow(32*3*window_size,2),1,10,100,2,0]);
                    ^

Error: If overriding default settings, must pass minDisparity, numDisparities, and SADWindowSize
    at Error (native)
    at /home/sagar/Repositories/MS/Grad_Project/stereo_match.js:28:21
    at /home/sagar/Repositories/MS/Grad_Project/stereo_match.js:22:6
    at Object.<anonymous> (/home/sagar/Repositories/MS/Grad_Project/stereo_match.js:21:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

Kindly help me out. Thank you
P.S : Im using Nodejs 4.2.6

**Comment by dvenkatsagar** [comment]
Ok I understood what the problem was: it should be done as `new StereoSGBM()` not just `StereoSGBM`

**Comment by Manu-shukla** [comment]
Can I ask are you trying to convert 2d images to 3d images?
