### ISSUE TITLE
error when install opencv-node on mac

### ISSUE THREAD

**Issue by thugasin** [peterbraden/node-opencv#363]
the error is as below, i deleted opencv 3.0 and change back to 2.4.1, then switch node version to 0.12, but still have such problem:

```
stcui:~ sirius$ npm install -g opencv-node
-
> opencv-node@0.2.6 install /Users/sirius/npm-global/lib/node_modules/opencv-node
> node-gyp configure build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/addon/src/addon.o
In file included from ../src/addon.cpp:3:
../src/bea.h:19:22: error: no member named 'ThrowException' in namespace 'v8'
                        m_exception = v8::ThrowException(v8::Exception::...
                                      ~~~~^
../src/bea.h:19:74: error: no member named 'NewSymbol' in 'v8::String'
  ...= v8::ThrowException(v8::Exception::TypeError(v8::String::NewSymbol(mess...
                                                   ~~~~~~~~~~~~^
../src/bea.h:31:22: error: no member named 'ThrowException' in namespace 'v8'
                        m_exception = v8::ThrowException(v8::Exception::...
                                      ~~~~^
../src/bea.h:31:74: error: no member named 'NewSymbol' in 'v8::String'
  ...= v8::ThrowException(v8::Exception::TypeError(v8::String::NewSymbol(s.st...
                                                   ~~~~~~~~~~~~^
../src/bea.h:119:32: error: no type named 'Arguments' in namespace 'v8'; did you
      mean 'v8::internal::Arguments'?
  ...static inline T FromJS(const v8::Arguments& args, int nArg, const T& def){
                                  ^~~~~~~~~~~~~
                                  v8::internal::Arguments
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/addon.cpp:3:
../src/bea.h:125:31: error: no type named 'Arguments' in namespace 'v8'; did you
      mean 'v8::internal::Arguments'?
                static inline bool Is(const v8::Arguments& args, int nArg){
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/addon.cpp:3:
../src/bea.h:120:12: error: member access into incomplete type 'const
      v8::internal::Arguments'
                        if (args.Length() > nArg)
                                ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
In file included from ../src/addon.cpp:3:
../src/bea.h:121:35: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
                                return Convert<T>::FromJS(args[nArg], nArg);
                                                          ~~~~^~~~~
../src/bea.h:126:12: error: member access into incomplete type 'const
      v8::internal::Arguments'
                        if (args.Length() > nArg)
                                ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
In file included from ../src/addon.cpp:3:
../src/bea.h:127:31: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
                                return Convert<T>::Is(args[nArg]);
                                                      ~~~~^~~~~
../src/bea.h:148:31: error: too few arguments to function call, expected 2, have
      1
                        return v8::Integer::New(val);
                               ~~~~~~~~~~~~~~~~    ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../src/addon.cpp:3:
../src/bea.h:169:30: error: too few arguments to function call, expected 2, have
      1
                        return v8::Number::New(val);
                               ~~~~~~~~~~~~~~~    ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:3: note: 'New' declared
      here
  static Local<Number> New(Isolate* isolate, double value);
  ^
In file included from ../src/addon.cpp:3:
../src/bea.h:203:31: error: too few arguments to function call, expected 2, have
      1
                        return v8::Boolean::New(val);
                               ~~~~~~~~~~~~~~~~    ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:6194:1: note: 'New' declared
      here
Handle<Boolean> Boolean::New(Isolate* isolate, bool value) {
^
In file included from ../src/addon.cpp:3:
../src/bea.h:220:25: error: no member named 'AsciiValue' in 'v8::String'
                        return  *v8::String::AsciiValue(v->ToString());
                                 ~~~~~~~~~~~~^
../src/bea.h:224:23: error: no member named 'New' in 'v8::String'
                        return v8::String::New (val.c_str());
                               ~~~~~~~~~~~~^
../src/bea.h:276:50: error: cannot initialize a parameter of type
      'v8::Isolate *' with an lvalue of type 'int'
                        v8::Local<v8::Array> jsArray = v8::Array::New(len);
                                                                      ^~~
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:36: note: passing
      argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
In file included from ../src/addon.cpp:3:
../src/bea.h:281:17: error: no member named 'Close' in 'v8::HandleScope'
                        return scope.Close(jsArray);
                               ~~~~~ ^
../src/bea.h:317:29: error: too few arguments to function call, expected 2, have
      1
                        return v8::Int32::New(val);
                               ~~~~~~~~~~~~~~    ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../src/addon.cpp:3:
../src/bea.h:335:30: error: too few arguments to function call, expected 2, have
      1
                        return v8::Uint32::New(val);
                               ~~~~~~~~~~~~~~~    ^
/Users/sirius/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/addon/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/sirius/npm-global/lib/node_modules/opencv-node
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "opencv-node"
npm ERR! node v0.12.0
npm ERR! nam  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! opencv-node@0.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
nam ERR!
npm ERR! Failed at the opencv-node@0.2.6 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the opencv-node package,
npm ERR! not with nam itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sirius/npm-debug.log
```

thanks for any suggestion.

**Comment by thugasin** [comment]
same issue  with #266
