### ISSUE TITLE
what node version is supported?

### ISSUE THREAD

**Issue by thugasin** [peterbraden/node-opencv#376]
for my machine, now only node 0.12.0 works fine. for the latest version 5.5.0, i got the error:

Cannot find module '/Users/sirius/JsCV/node-opencv/build/opencv/v5.0.0/Release/node-v47-darwin-x64/opencv.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/sirius/JsCV/node-opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

I'm use the max os, now i have to user the latest node version for my project, any idea on this ?

**Comment by jamesmoey** [comment]
I ran on node v5.3.0 last week fine.

**Comment by peterbraden** [comment]
Are you sure you ran npm install with the current version? It looks like it can't find compiled targets for your version.

**Comment by thugasin** [comment]
thanks for the answer, after i reinstall node and opencv, the problem fixed.

my node version now is 4.3.0
