### ISSUE TITLE
Issue installing under Node v5.6.0

### ISSUE THREAD

**Issue by cdekok** [peterbraden/node-opencv#384]
I get the following errors when i try to install it.

```
/home/chris/www/node-cv/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /home/chris/www/node-cv/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/chris/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-30-generic
gyp ERR! command "/home/chris/.nvm/versions/node/v5.6.0/bin/node" "/home/chris/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64"
gyp ERR! cwd /home/chris/www/node-cv/node_modules/opencv
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/chris/.nvm/versions/node/v5.6.0/bin/node /home/chris/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64/opencv.node --module_name=opencv --module_path=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/chris/www/node-cv/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.2.0-30-generic
node-pre-gyp ERR! command "/home/chris/.nvm/versions/node/v5.6.0/bin/node" "/home/chris/www/node-cv/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/chris/www/node-cv/node_modules/opencv
node-pre-gyp ERR! node -v v5.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
Failed to execute '/home/chris/.nvm/versions/node/v5.6.0/bin/node /home/chris/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64/opencv.node --module_name=opencv --module_path=/home/chris/www/node-cv/node_modules/opencv/build/opencv/v5.0.0/Release/node-v47-linux-x64' (1)
npm WARN node-cv@1.0.0 No description
npm WARN node-cv@1.0.0 No repository field.
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/home/chris/.nvm/versions/node/v5.6.0/bin/node" "/home/chris/.nvm/versions/node/v5.6.0/bin/npm" "install" "opencv" "--install"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chris/www/node-cv/npm-debug.log
```

**Comment by cdekok** [comment]
my bad i still needed to install opencv..

```
apt-get install libopencv-dev
```
