### ISSUE TITLE
undefined symbol: _ZN7QWidget13keyPressEventEP9QKeyEvent 

### ISSUE THREAD

**Issue by rondagdag** [peterbraden/node-opencv#396]
I was able to install node opencv in creator ci20 with node 4.4.3 and opencv 2.4.11
it was able to build node opencv
but when I tried running it, I get an error

module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/ci20/opencvnodebot/node_modules/opencv/build/opencv/v5.0.0/Release/node-v46-linux-mipsel/opencv.node: undefined symbol: _ZN7QWidget13keyPressEventEP9QKeyEvent
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ci20/opencvnodebot/node_modules/opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Opencv works in python. I installed Qt5-dev and qt4-dev. I also tried older version of node-opencv, and does not work.
Is there a way to skip this module?

Thanks,

**Comment by mcwhittemore** [comment]
@rondagdag are you using Homebrew to install opencv? I ran into this same problem that way. In the end my solution (read hack) was to modify the `/utils/find-opencv.js` to use the homebrew version of pkg-config.
