### ISSUE TITLE
Symbol Not Found when trying to use OpenCV

### ISSUE THREAD

**Issue by raghunat** [peterbraden/node-opencv#409]
Hello!

I am receiving the following error when trying to use this on a fresh installation of opencv 2.4.12 on Mac El Capitan

Node: 4.4.4
NPM: 2.15.1
node-opencv: 5.0.0

```
Error: dlopen(/Users/stephenraghunath/Desktop/WorkWork/q4/jackson/sandbox/openseevee/node_modules/opencv/build/opencv/v5.0.0/Release/node-v46-darwin-x64/opencv.node, 1): Symbol not found: _OBJC_CLASS_$_NSApplication
  Referenced from: /Users/stephenraghunath/Desktop/WorkWork/q4/jackson/sandbox/openseevee/node_modules/opencv/build/opencv/v5.0.0/Release/node-v46-darwin-x64/opencv.node
  Expected in: dynamic lookup

    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/stephenraghunath/Desktop/WorkWork/q4/jackson/sandbox/openseevee/node_modules/opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Any pointers for me to resolve? I have been scouring the internet for solutions, but have turned up empty.

Regards,
Stephen

**Comment by raghunat** [comment]
Adding installation stdout:

```
openseevee $ npm install opencv
npm WARN package.json openseevee@1.0.0 No description
npm WARN package.json openseevee@1.0.0 No repository field.
npm WARN package.json openseevee@1.0.0 No README data
\
> opencv@5.0.0 install /Users/stephenraghunath/Desktop/WorkWork/q4/jackson/sandbox/openseevee/node_modules/opencv
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
../src/FaceRecognizer.cc:5:2: warning: TODO: port me to OpenCV 3 [-W#warnings]
#warning TODO: port me to OpenCV 3
 ^
1 warning generated.
  CXX(target) Release/obj.target/opencv/src/Features2d.o
  CXX(target) Release/obj.target/opencv/src/BackgroundSubtractor.o
../src/BackgroundSubtractor.cc:7:2: warning: TODO: port me to OpenCV 3 [-W#warnings]
#warning TODO: port me to OpenCV 3
 ^
1 warning generated.
  CXX(target) Release/obj.target/opencv/src/Constants.o
  CXX(target) Release/obj.target/opencv/src/Calib3D.o
  CXX(target) Release/obj.target/opencv/src/ImgProc.o
  CXX(target) Release/obj.target/opencv/src/Stereo.o
../src/Stereo.cc:5:2: warning: TODO: port me to OpenCV 3 [-W#warnings]
#warning TODO: port me to OpenCV 3
 ^
1 warning generated.
  CXX(target) Release/obj.target/opencv/src/LDAWrap.o
../src/LDAWrap.cc:4:2: warning: TODO: port me to OpenCV 3 [-W#warnings]
#warning TODO: port me to OpenCV 3
 ^
1 warning generated.
  SOLINK_MODULE(target) Release/opencv.node
ld: warning: object file (Release/obj.target/opencv/src/init.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/OpenCV.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: ld: warning: object file (Release/obj.target/opencv/src/Matrix.o) was built for newer OSX version (10.7) than being linked (10.5)object file (Release/obj.target/opencv/src/CascadeClassifierWrap.o) was built for newer OSX version (10.7) than being linked (10.5)

ld: warning: object file (Release/obj.target/opencv/src/Contours.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/Point.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/VideoCaptureWrap.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/CamShift.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/HighGUI.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/FaceRecognizer.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/Features2d.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/BackgroundSubtractor.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/Constants.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (Release/obj.target/opencv/src/ImgProc.o) was built for newer OSX version (10.7) than being linked (10.5)ld: warning: ld: warning: 
object file (Release/obj.target/opencv/src/Calib3D.o) was built for newer OSX version (10.7) than being linked (10.5)object file (Release/obj.target/opencv/src/Stereo.o) was built for newer OSX version (10.7) than being linked (10.5)

ld: warning: object file (Release/obj.target/opencv/src/LDAWrap.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(convhull.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(shapedescr.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(smooth.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(imgwarp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(hough.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(arithm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(rotcalipers.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_highgui.a(window.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_videoio.a(cap.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(approx.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(drawing.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(histogram.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(contours.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(templmatch.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(calibration.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(copy.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_objdetect.a(cascadedetect.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(thresh.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(featureselect.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(calibinit.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(morph.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(undistort.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(fundam.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matop.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(canny.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(deriv.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(system.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(convert.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(pyramids.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(loadsave.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(moments.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_video.a(camshift.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(color.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(alloc.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(solvepnp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(floodfill.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_highgui.a(window_cocoa.mm.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_videoio.a(cap_qtkit.mm.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_objdetect.a(haar.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_videoio.a(cap_images.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(circlesgrid.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(filter.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_bmp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_exr.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_hdr.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_png.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_pxm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(tables.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(mathfuncs.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(persistence.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_jpeg.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_tiff.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_webp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(demosaicing.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(corner.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(dxt.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_jpeg2000.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(parallel.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(levmarq.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(hershey_fonts.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_sunras.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(rho.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_videoio.a(cap_mjpeg_encoder.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_videoio.a(cap_mjpeg_decoder.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(ptsetreg.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(lapack.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(merge.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(split.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(ocl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opencl_kernels_core.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(opencl_kernels_imgproc.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_objdetect.a(opencl_kernels_objdetect.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opengl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(umatrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_gpu_mat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_stream.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_host_mem.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(epnp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matmul.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(kmeans.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(sumpixels.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(algorithm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(p3p.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(compat_ptsetreg.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(array.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(datastructs.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(checkchessboard.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(cornersubpix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(utils.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(tables.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_calib3d.a(polynom_solver.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(utils.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(rgbe.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(jpeg_exif.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(bitstrm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(samplers.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(grfmt_base.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(geometry.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(pca.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(mathfuncs_core.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matrix_decomp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_flann.a(miniflann.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(rand.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(out.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
  COPY /Users/stephenraghunath/Desktop/WorkWork/q4/jackson/sandbox/openseevee/node_modules/opencv/build/opencv/v5.0.0/Release/node-v46-darwin-x64/opencv.node
  TOUCH Release/obj.target/action_after_build.stamp
  CXX(target) Release/obj.target/test_nativemat/test/nativemat.o
  SOLINK_MODULE(target) Release/test_nativemat.node
ld: warning: object file (Release/obj.target/test_nativemat/test/nativemat.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(alloc.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(convert.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(tables.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(system.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(copy.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(ocl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opencl_kernels_core.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opengl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(umatrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_gpu_mat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_stream.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_host_mem.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(kmeans.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matop.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(array.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(datastructs.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(arithm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(parallel.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(merge.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(split.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matmul.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(lapack.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(rand.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(persistence.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(pca.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matrix_decomp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
```

**Comment by danschultzer** [comment]
How did you install opencv? You used homebrew?

**Comment by raghunat** [comment]
Yes this was through homebrew at the time. I believe this is resolved now. I had unintstalled alot of homebrew items and when I went back to it, it worked.
