### ISSUE TITLE
How to test newly added methods locally?

### ISSUE THREAD

**Issue by kuldarim** [peterbraden/node-opencv#427]
Hey,

I wanted to add `getGaborKernel` method to `node-opencv`. After digging into some of PR's I have found a way how to extend `ImgProc.cc` and add a new method. But now I'm facing a problem with running tests locally. 
I have added a simple example, just to make sure that my newly added method was exported correctly. 
```
var cv = require('../lib/opencv');
console.log(cv.getGaborKernel());
```
and while running `npm test` I get following error 

```
# Example: ./examples/getGaborKernel.js
not ok 99 Error: Command failed: node /Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js /Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js:5 console.log(cv.getGaborKernel()); ^ TypeError: cv.getGaborKernel is not a function at Object.<anonymous> (/Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js:5:16) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Function.Module.runMain (module.js:575:10) at startup (node.js:160:18) at node.js:449:3
  ---
    operator: error
    expected:
      undefined
    actual:
      { cmd: 'node /Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js', code: 1, killed: false, signal: null }
    at: maybeClose (internal/child_process.js:850:16)
    stack:
      Error: Command failed: node /Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js
    /Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js:5
    console.log(cv.getGaborKernel());
                   ^

    TypeError: cv.getGaborKernel is not a function
        at Object.<anonymous> (/Users/kuldarim/Projects/node-opencv/examples/getGaborKernel.js:5:16)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Function.Module.runMain (module.js:575:10)
        at startup (node.js:160:18)
        at node.js:449:3

        at ChildProcess.exithandler (child_process.js:202:12)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:850:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  ...
```

It seams for me that my newly added method is not added at all. So maybe there are some steps  or instructions which are needed to do while adding new methods and testing them locally?

FYI: [my newly added method diff](https://github.com/kuldarim/node-opencv/commit/b5c99f635a45b6565f9dbde27bbf05a92072bb9b)

**Comment by danschultzer** [comment]
Try call it with `cv.imgproc.getGaborKernel()`.
