### ISSUE TITLE
heroku nodejs opencv

### ISSUE THREAD

**Issue by hhertogh** [peterbraden/node-opencv#429]
Hello,

I'm trying to use it on heroku.
I set the different buildpacks in a .buildpacks file:
https://github.com/juliobarreraa/heroku-buildpack-opencv
https://github.com/heroku/heroku-buildpack-nodejs

It builds and deploys but when I run the app and import the node opencv module, I got the following error from the logs:

State changed from starting to crashed
2016-07-30T14:43:54.664098+00:00 heroku[web.1]: Process exited with status 1
2016-07-30T14:43:54.580588+00:00 app[web.1]: module.js:440
2016-07-30T14:43:54.580603+00:00 app[web.1]:   return process.dlopen(module, path._makeLong(filename));
2016-07-30T14:43:54.580604+00:00 app[web.1]:                  ^
2016-07-30T14:43:54.580605+00:00 app[web.1]: 
2016-07-30T14:43:54.580606+00:00 app[web.1]: Error: libjpeg.so.62: cannot open shared object file: No such file or directory
2016-07-30T14:43:54.580607+00:00 app[web.1]:     at Error (native)
2016-07-30T14:43:54.580607+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:440:18)
2016-07-30T14:43:54.580608+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-30T14:43:54.580609+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-07-30T14:43:54.580609+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-07-30T14:43:54.580610+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-07-30T14:43:54.580610+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/opencv/lib/bindings.js:4:15)
2016-07-30T14:43:54.580611+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-07-30T14:43:54.580612+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-07-30T14:43:54.580612+00:00 app[web.1]:     at Module.load (module.js:357:32)

Do you know what is the issue?
Thanks

**Comment by danschultzer** [comment]
> 2016-07-30T14:43:54.580606+00:00 app[web.1]: Error: libjpeg.so.62: cannot open shared object file: No such file or directory

Seems like you don't have `libjpeg.so`? Just install `libjpeg62`.
