### ISSUE TITLE
node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-win32-x64.tar.gz

### ISSUE THREAD

**Issue by mukulsoftwap** [peterbraden/node-opencv#463]
node version : 6.9.1
npm version : 3.10.8

when install open cv in windows error comes : node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-win32-x64.tar.gz

> opencv@6.0.0 install C:\Users\mukulsoftwap\Desktop\node-opencv-master
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)

C:\Users\mukulsoftwap\Desktop\node-opencv-master>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\mukulsoftwap\Desktop\node-opencv-master>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\mukulsoftwap\AppData\Local\Programs\Python\Python35-32", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\mukulsoftwap\\Desktop\\node-opencv-master\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Users\\mukulsoftwap\\Desktop\\node-opencv-master\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\mukulsoftwap\Desktop\node-opencv-master
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\mukulsoftwap\Desktop\node-opencv-master\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mukulsoftwap\\Desktop\\node-opencv-master\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\mukulsoftwap\Desktop\node-opencv-master
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\node-opencv-master\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mukulsoftwap\Desktop\node-opencv-master\npm-debug.log

**Comment by vinnitu** [comment]
$ wget https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v11-linux-x64.tar.gz
--2016-11-09 10:24:41--  https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v11-linux-x64.tar.gz
Resolving node-opencv.s3.amazonaws.com (node-opencv.s3.amazonaws.com)... 54.231.73.27
Connecting to node-opencv.s3.amazonaws.com (node-opencv.s3.amazonaws.com)|54.231.73.27|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-11-09 10:24:42 ERROR 403: Forbidden.

**Comment by mlison** [comment]
I'm having the same problem.

**Comment by 821760408-sp** [comment]
@mukulsoftwap 
Try installing with --build-from-source, i.e.:
`npm install opencv --build-from-source`

**Comment by slinto** [comment]
+1

**Comment by jaymehtasa** [comment]
+1

`NodeJS` - `v5.5.0`
`npm` - `v4.0.2`
`MacOS` - `10.11.3`

**Comment by cheshire137** [comment]
I'm experiencing this in macOS Sierra with npm 3.10.3 and node 6.3.1:

```
% npm install opencv --save

> opencv@6.0.0 install /Users/me/my-project/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp)
/Users/me/my-project/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/me/my-project/node_modules/opencv/utils/find-opencv.js:21:23
```

**Comment by wassgha** [comment]
^ Same

**Comment by HabibMAALEM** [comment]
Error installing opencv, npm 3.5.2 node 7.2.1

> opencv@6.0.0 install /home/maalem/Projects/carecrute/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@7.2.1 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by manzato** [comment]
Same problem

**Comment by JSProto** [comment]
^ same

**Comment by bharath063** [comment]
Same problem.

**Comment by alienshop** [comment]
Hi, on Linux you can try to install the following:
`sudo apt-get install libopencv-dev`

It solved it for me. Basically the issue is that we are missing the opencv.pc or opencv3.pc files.

**Comment by lpgray** [comment]
brew install pkg-config
npm install opencv --save

solved my problem.

**Comment by padiarushi3012** [comment]
someone please solve this !

**Comment by johns24** [comment]
^Same

**Comment by jeevanhr7** [comment]
I'm using  macOS Sierra with 3.10.10 npm and node v6.10.0 i am also Facing the Same Problem, can anybody having the Solution for this.
 opencv@3.2.0 install /Users/jeevan/Projects/face-detection-nodejs/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@3.2.0 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:12:
In file included from ../../nan/nan.h:111:
../../nan/nan_new.h:34:56: warning: 'ToInt32' is deprecated [-Wdeprecated-declarations]
To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }

**Comment by fdambrosio** [comment]
same problem

**Comment by pnthach95** [comment]
Same problem.

**Comment by alliancenikolay** [comment]
Same problem

**Comment by micsun-al** [comment]
Meow.

**Comment by callmesoul** [comment]
same。
I user `npm install opencv --build-from-source`  solve this
in Ubuntu and run  `sudo apt-get install libopencv-dev`

**Comment by tedtang77** [comment]
same problem. any good solution for windows?

**Comment by btsimonh** [comment]
hi ted, there is a whole variety of issues in this 'issue', so please be more explicit.
Above we have people who:
have no development environment - one is required.
have no python or incorrectly configured - looks like it's required.

I don't think the pre-built binaries are there for any architecture at the moment; so it will always show that error and fallback to build, for which you will need the complete opencv dev package (e.g. [3.3.1](https://opencv.org/releases.html) worked for me), plus a working c++ compilation environment for node (for windows, the msbuild stuff works for me, but don't ask me how I installed it!.), plus don't forget the an env variable for where to find opencv...

**Comment by velykov** [comment]
not found zopfli-v2.0.1-node-v59-win32-x64.tar.gz

**Comment by btsimonh** [comment]
pls ignore the error about download of the pre-build; it will build from source.

**Comment by thomasphilibert** [comment]
Same here

**Comment by ClaudeSutterlin** [comment]
For the sake of future trouble shooting - If you're doing this on Heroku make sure that the opencv buildpack is listed first (before node.js buildpack). I also had to change my stack to cedar to get around another issue (ie `heroku stack:set cedar-14`)

**Comment by Kamill90** [comment]
is there any solution for it? 
npm ERR! Failed at the node-zopfli@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Errors are quite crucial since it is not possible to install any dep with npm.

**Comment by Kamill90** [comment]
@nyaapass 

is it Japanese? How is it supposed to help me?

**Comment by ClaudeSutterlin** [comment]
@Kamill90 I don't think node-opencv has a dependency on node-zopfli. I would check what needs it and try to trouble shoot it with the dependency that's causing the issue.

**Comment by creativefull** [comment]
1. clone node-opencv in folder node_modules
2. npm install

that worked for me (Y)

**Comment by mrpatel15** [comment]
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error

**Comment by billbarni** [comment]
Having this problem for weeks now, no fixes, Tried A LOT of things. Reinstalled node, removed everything and rebuilt... nothing. Problem persists. Amazing debug log... no clue whatsoever how to solve this.

**Comment by harryyuanfeng** [comment]
Same problem

**Comment by mrpatel15** [comment]
fixed.



Regards,
Mrugesh Patel

*ABOUT THIS E-MAIL*: The information transmitted is intended only for the
person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender and delete the material
from any computer.

**Comment by randomsock** [comment]
@mrpatel15 "fixed"?  Can you say how?  It would help a lot - still having this problem, on Linux (CentOS 6 and 7, Node 8)

**Comment by vsrusti** [comment]
@mrpatel15 : Could you share fix details? I tried various suggestions.. Nothing worked out for me. I'm using mac.

**Comment by mrpatel15** [comment]
are you guys using firebase with angular 4/5 ? if yes than pls configure your environments. 
and first pls uninstall npm and angular/cli and reinstall. 
and  setup account with firebase and add in below script tag in your environments.ts

<script src="https://www.gstatic.com/firebasejs/4.13.0/firebase.js"></script>
<script>
  // Initialize Firebase
  // TODO: Replace with your project's customized code snippet
  var config = {
    apiKey: "<API_KEY>",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
    projectId: "<PROJECT_ID>",
    storageBucket: "<BUCKET>.appspot.com",
    messagingSenderId: "<SENDER_ID>",
  };
  firebase.initializeApp(config);
</script>

**Comment by mrpatel15** [comment]
See here how to configure with firebase app + angular/cli -
_https://github.com/codediodeio/angular-firestarter/blob/master/src/environments/environment.ts_

**Comment by qewee** [comment]
I have the same problem, but I don't use firebase nor angular.

**Comment by IAmVinnnn** [comment]
I tried to setup opencv package on window system, Once I try with **npm i opencv --save** and got "node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-win32-x64.tar.gz" issue, Then I tried with **npm i opencv --build-from-source** and got "Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or directory, scandir 'C:\opencv\build\lib'" error.
Where as lib directory exist in the "C:\opencv\build\x64\vc15" location. 
I was setup an environment variable "OPENCV_DIR" with the value "C:\opencv\build".
Can anyone help me to fix the issue. I tried many solutions but not getting fix it.

**Comment by randomsock** [comment]
Not sure if this will help anyone, but in my case I got it working by completely removing the old `node_modules/opencv` from previous attempts, and then installing manually:

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/; pkg-config --cflags opencv; npm install opencv@6.*
```

**Comment by mrzool** [comment]
Still unable to install `node-opencv` on macOS.

After installing OpenCV and performing all the steps required, `npm install opencv` still fails with:

```
> opencv@6.0.0 install /Users/zool/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```

Any help is appreciated. @peterbraden @danschultzer

**Comment by zjuwjf** [comment]
^Same

**Comment by mrzool** [comment]
Managed to install `node-opencv` on macOS by doing the following:

1. `git clone git@github.com:peterbraden/node-opencv.git` 
2. `cd node-opencv`
3. `make`
4. `npm install`
5. `npm install -g`

Got a ton of warnings from both `make` and `npm`, but the library seems now to be available to programs requiring it. No idea if all the above steps are actually required, just reporting here for posterity.

**Comment by guignol1981** [comment]
1. remove package-lock.json
2. remove node_modules
3. npm install

**Comment by acandael** [comment]
I also have this problem on:

Node v10.13.0
MacOS 10.14.6 (Mojave)

Tried all of the above, nothing solved the problem.
Still getting this error:

> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)

Does anyone have a solution for this?
