### ISSUE TITLE
ERROR: failed to run: pkg-config

### ISSUE THREAD

**Issue by serganus** [peterbraden/node-opencv#482]
I tried installing : 
- `$ brew tap homebrew/science` (No errors)
- `$ brew install opencv` (No errors)
- `$ npm install --save opencv` (Got errors)

What i got is : 

```
> opencv@6.0.0 install /Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.9.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64"
gyp ERR! cwd /Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv
node-pre-gyp ERR! node -v v6.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/gautamanand/Github/serganus/VisionNodejs/node_modules/opencv/build/opencv/v6.0.0/Release/node-v48-darwin-x64' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.32
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "opencv"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gautamanand/Github/serganus/VisionNodejs/npm-debug.log
```

# Any leads to fix it will be great!

**Comment by masonicGIT** [comment]
Had the same issue but with opencv installed differently.

**Comment by serganus** [comment]
@masonicGIT did u find a fix?

**Comment by masonicGIT** [comment]
@serganus - Not sure of the root cause. Work-around is to install opencv with brew.

**Comment by Schultzer** [comment]
@serganus have to checked if `opencv.pc` is in your `pkgconfig` sould be located at `usr/local/lib/pkgconfig/opencv.pc`
if not try to `brew link opencv` or `brew link --force opencv`

**Comment by barczaG** [comment]
`brew install pkg-config` did the trick for me

**Comment by danielbh** [comment]
Don't forget to reinstall node modules

**Comment by CoolCheetah1** [comment]
@Schultzer I keep getting Error: No such keg: /usr/local/Cellar/opencv.pc when I try to `brew link opencv` or `brew link --force opencv`

**Comment by SarjuHansaliya** [comment]
I am using Mac
`export PKG_CONFIG_PATH=/usr/local/opt/opencv@2/lib/pkgconfig`
did the trick for me

**Comment by eth4kr** [comment]
Anyone please help, having same error, i have installed opencv on my Linux Mint

**Comment by MarkkNijboer** [comment]
I had the same issue on my Raspberry Pi with a pre-compiled version of OpenCV. OpenCV was installed but it didn't show up in pkg-config. I fixed the issue by making my own `opencv.pc` in `/usr/lib/pkgconfig`. The pre-compiled `.so`-files of OpenCV were located in `/usr/local/lib/opencv/lib` and the C-includes were in `/usr/local/lib/opencv/include`. 

My `opencv.pc` looked like this:
___________________________________________
prefix=/usr/local/lib/opencv
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: opencv
Description: The OpenCV library
Version: 3.2.0
Cflags: -I${includedir}
Libs: -L${libdir} -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_calib3d -lopencv_ccalib -lopencv_core -lopencv_datasets -lopencv_dnn -lopencv_dpm -lopencv_face -lopencv_features2d -lopencv_flann -lopencv_freetype -lopencv_fuzzy -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_line_descriptor -lopencv_ml -lopencv_objdetect -lopencv_optflow -lopencv_phase_unwrapping -lopencv_photo -lopencv_plot -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_stitching -lopencv_structured_light -lopencv_superres -lopencv_surface_matching -lopencv_text -lopencv_tracking -lopencv_video -lopencv_videoio -lopencv_videostab -lopencv_xfeatures2d -lopencv_ximgproc -lopencv_xobjdetect -lopencv_xphoto
_________________

So I basically linked every .so file that I found in `/usr/local/lib/opencv/lib`. 

When I ran `pkg-config opencv --exists` and `echo $?` afterwards, it returned 0. `node-opencv` ended up working as well.

**Comment by k1berg** [comment]
> Anyone please help, having same error, i have installed opencv on my Linux Mint

did you find a solve?
