### ISSUE TITLE
WIN8 -- fatal error C1021: invalid preprocessor command 'warning'

### ISSUE THREAD

**Issue by Haskman** [peterbraden/node-opencv#488]
```
..\src\BackgroundSubtractor.cc(7): fatal error C1021: invalid preprocessor comm
and 'warning' [C:\Users\Victor\node_modules\opencv\build\opencv.vcxproj]
..\src\Stereo.cc(5): fatal error C1021: invalid preprocessor command 'warning'
[C:\Users\Victor\node_modules\opencv\build\opencv.vcxproj]
c:\users\victor\node_modules\opencv\node_modules\nan\nan_new.h(208): warning C4
267: 'argument' : conversion from 'size_t' to 'int', possible loss of data (..\
src\Calib3D.cc) [C:\Users\Victor\node_modules\opencv\build\opencv.vcxproj]
          ..\src\Calib3D.cc(144) : see reference to function template instantia
  tion 'v8::Local<v8::Array> Nan::New<v8::Array,unsigned __int64>(A0)' being co
  mpiled
          with
          [
              A0=unsigned __int64
          ]
  LDAWrap.cc
..\src\LDAWrap.cc(4): fatal error C1021: invalid preprocessor command 'warning'
 [C:\Users\Victor\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Use
rs\\Victor\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v14-win32
-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Users\\Victor\\node
_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v14-win32-x64"
gyp ERR! cwd C:\Users\Victor\node_modules\opencv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=C:\Users\Victor\node_modules\opencv\build\opencv\v6.0.0\Releas
e\node-v14-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\Vic
tor\node_modules\opencv\build\opencv\v6.0.0\Release\node-v14-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Victor\node_mo
dules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.2.9200
node-pre-gyp ERR! command "node" "C:\\Users\\Victor\\node_modules\\opencv\\node_
modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Victor\node_modules\opencv
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Vict
or\node_modules\opencv\build\opencv\v6.0.0\Release\node-v14-win32-x64\opencv.nod
e --module_name=opencv --module_path=C:\Users\Victor\node_modules\opencv\build\o
pencv\v6.0.0\Release\node-v14-win32-x64' (1)
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Victor\npm-debug.log

```

[npm-debug.txt](https://github.com/peterbraden/node-opencv/files/775758/npm-debug.txt)

**Comment by FrogTheFrog** [comment]
OpenCV 3.x.x is not supported. Use OpenCV 2.4.13 and the error should go away.
