### ISSUE TITLE
Getting errors related to 3.2 while having 2.4 installed

### ISSUE THREAD

**Issue by Cyberuben** [peterbraden/node-opencv#508]
When I try to `require()` the `opencv` module, I get the following error:

```
Error: libopencv_objdetect.so.3.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ruben/Projects/opencv-test/node_modules/opencv/lib/bindings.js:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

I have installed the `2.4` version of OpenCV, and `cat /usr/local/lib/pkgconfig/opencv.pc` shows version `2.4.13.2`. Why is it looking for 3.2?

This is on Ubuntu 16.04

**Comment by faustofjunqueira** [comment]
What's solution?

**Comment by Cyberuben** [comment]
I ended up removing everything related to opencv, and reinstalling all the dependencies step by step, making sure I have the right versions.

**Comment by faustofjunqueira** [comment]
My problem was in env variable ld_library_path

Em sáb, 1 de jul de 2017 20:42, Ruben Rutten <notifications@github.com>
escreveu:
