### ISSUE TITLE
Can't install OpenCV 2.3.1 on OS X 10.8.3. I couldn't identify the problem. Will later OpenCV work with node-opencv?

### ISSUE THREAD

**Issue by vgm106** [peterbraden/node-opencv#52]
**UPDATE:** I went ahead and installed OpenCV 2.4.5 and tried to install node-opencv. I got the following 

```
npm http GET https://registry.npmjs.org/opencv
npm http 200 https://registry.npmjs.org/opencv
npm http GET https://registry.npmjs.org/opencv/-/opencv-0.1.0.tgz
npm http 200 https://registry.npmjs.org/opencv/-/opencv-0.1.0.tgz
npm WARN package.json opencv@0.1.0 No repository field.

> opencv@0.1.0 preinstall /Users/madhu/node_modules/opencv
> node-gyp clean rebuild

gyp http GET http://nodejs.org/dist/v0.10.9/node-v0.10.9.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.9/node-v0.10.9.tar.gz
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
gyp: Call to 'pkg-config --cflags opencv' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:415:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "rebuild"
gyp ERR! cwd /Users/madhu/node_modules/opencv
gyp ERR! node -v v0.10.9
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by SlightlyCyborg** [comment]
Yes. Have tried <code>brew install opencv</code> Same errors occur upon npm install opencv

**Comment by rafaneri** [comment]
Hello,

I've had this problem too.
So searching on the web I found this [tutorial](http://tilomitra.com/opencv-on-mac-osx/). I did the opencv reinstall and now npm install opencv works fine!

The important details are:
make -j8
sudo make install

To build OpenCv in your /usr/local/ directory.

**Comment by dokuboyejo** [comment]
Hi Collin,

You can follow the link <http://tilomitra.com/opencv-on-mac-osx/> provided
by Rafael or use this one
<http://stackoverflow.com/questions/18122724/setting-installing-up-opencv-2-4-6-1-on-ubuntu-12-04-02>
that
I created sometimes ago on stackoverflow




---------------------------

Kind Regards!

*D*amilola *A. Okuboyejo*  (MBCS, MCSSA/MIITPSA, MIAENG)
