### ISSUE TITLE
[URGENT] Unable to install node-opencv on my ubuntu live server

### ISSUE THREAD

**Issue by balachandra** [peterbraden/node-opencv#55]
HI There,

 After working with node-opencv on my mac and completed feature validation and when i try to deploy on my live ubuntu box which powers my website www.thply.com its throwing me following error. due to this my website is down for past two days please help.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libopencv_contrib.so.2.4: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bala/thply/node_modules/opencv/lib/bindings.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Forever restarting script for 1 time

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libopencv_contrib.so.2.4: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bala/thply/node_modules/opencv/lib/bindings.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
pkg-config --cflags opencv^Cbala@li253-244:~/thply$ pkg-config --cflags opencv
-I/usr/local/include/opencv -I/usr/local/include  
bala@li253-244:~/thply$ 

bala@li253-244:~/thply$ sudo locate libopencv_contrib.so.2.4
/home/bala/opencv-2.4.2/OpenCV-2.4.2/build/lib/libopencv_contrib.so.2.4
/home/bala/opencv-2.4.2/OpenCV-2.4.2/build/lib/libopencv_contrib.so.2.4.2
/home/bala/opencv-2.4.5/build/lib/libopencv_contrib.so.2.4
/home/bala/opencv-2.4.5/build/lib/libopencv_contrib.so.2.4.5
/home/bala/opencv-2.4.5/release/lib/libopencv_contrib.so.2.4
/home/bala/opencv-2.4.5/release/lib/libopencv_contrib.so.2.4.5
/home/bala/opencv-x/OpenCV-2.4.2/release/lib/libopencv_contrib.so.2.4
/home/bala/opencv-x/OpenCV-2.4.2/release/lib/libopencv_contrib.so.2.4.2
/usr/local/lib/libopencv_contrib.so.2.4
/usr/local/lib/libopencv_contrib.so.2.4.5

Thank you,
-bala.

**Comment by danschultzer** [comment]
I believe this is a deprecated issue. I'll close it for now.
