### ISSUE TITLE
Cannot find module 'buffers' 

### ISSUE THREAD

**Issue by BTEVC** [peterbraden/node-opencv#553]
New to node.js and opencv. Trying to run face-detection.js in the examples on MacOSX Sierra in Terminal like this: 

$ node face-detection.js

Getting this error: 

Error: Cannot find module 'buffers'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/BTEVC/07 TSAD/OpenCV/node-opencv-master/lib/opencv.js:2:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

Can anyone give some tips on how to fix this, or if I'm missing something? Tried to reinstall both node and opencv in Terminal, but to no avail. Am I lacking some basic understanding of how this is supposed to work?

**Comment by TysonPark** [comment]
Running npm install in the node-opencv directory fixed this for me.
`$ npm install`
