### ISSUE TITLE
node-pre-gyp install --fallback-to-build on MacBook

### ISSUE THREAD

**Issue by JonasWestAlro** [peterbraden/node-opencv#561]
Hi, 

When running "npm install opencv" on my MacBook Sierra I get: 
```

Jonas:app jonaswestalro$ npm install opencv

> opencv@6.0.0 install /Users/jonaswestalro/Desktop/Software/app/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.11.4 (node-v48 ABI) (falling back to source compile with node-gyp) 
/Users/jonaswestalro/Desktop/Software/app/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/jonaswestalro/Desktop/Software/app/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
...
...
```

I've tried the solution suggested here: https://github.com/peterbraden/node-opencv/issues/543 but without luck. 

And I've made sure the the "pkg-config" is installed through brew.

**Comment by JonasWestAlro** [comment]
export PKG_CONFIG_PATH=/usr/local/opt/opencv@2/lib/pkgconfig 
npm install opencv

did the trick as suggested in https://github.com/peterbraden/node-opencv/issues/482 @SarjuHansaliya
