### ISSUE TITLE
I can't install node-opencv in macOs Sierra

### ISSUE THREAD

**Issue by muhammadsamir11** [peterbraden/node-opencv#562]
Error: lib for module 'imgcodecs' not found in OPENCV_LIB_DIR ('/usr/local/lib')

**Comment by limichange** [comment]
So many error infomation. 🙄
<details>

```

error /Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.17
node-pre-gyp info using node@8.8.1 | darwin | x64
node-pre-gyp info check checked for "/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node" (not found)
node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz (falling back to source compile with node-gyp)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/limi/.node-gyp/8.8.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/limi/.node-gyp/8.8.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/limi/.node-gyp/8.8.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/opencv/src/init.o
  CXX(target) Release/obj.target/opencv/src/Matrix.o
../src/Matrix.cc:335:59: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Object> actualBuffer = bufferConstructor->NewInstance(3, constructorArgs);
                                                          ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3831:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:500:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:522:55: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                      ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:672:62: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local < v8::Object > actualBuffer = bufferConstructor->NewInstance(3,
                                                             ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3831:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:708:61: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> actualBuffer = bufferConstructor->NewInstance(3, constructorArgs);
                                                            ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3831:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1022:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im_h = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1037:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im_h = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1052:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im_h = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1191:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1205:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1222:27: warning: 'ToInt32' is deprecated [-Wdeprecated-declarations]
  int flipCode = info[0]->ToInt32()->Value();
                          ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:2331:10: note: 'ToInt32' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Int32> ToInt32() const);
         ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1224:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> img_to_return = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1241:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> img_to_return = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1466:81: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> conts_to_return= Nan::New(Contour::constructor)->GetFunction()->NewInstance();
                                                                                ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1662:26: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  float angle = info[0]->ToNumber()->Value();
                         ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:2323:10: note: 'ToNumber' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1712:26: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  float angle = info[0]->ToNumber()->Value();
                         ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:2323:10: note: 'ToNumber' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1718:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1882:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1901:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1916:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> mean = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:1918:72: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> stddev = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                       ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:2079:55: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                      ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:2259:69: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> out = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:2293:69: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> out = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:2451:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> xfrm = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Matrix.cc:2609:53: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                    ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
26 warnings generated.
  CXX(target) Release/obj.target/opencv/src/OpenCV.o
../src/OpenCV.cc:24:70: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im_h = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                     ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/opencv/src/CascadeClassifierWrap.o
  CXX(target) Release/obj.target/opencv/src/Contours.o
  CXX(target) Release/obj.target/opencv/src/Point.o
  CXX(target) Release/obj.target/opencv/src/VideoCaptureWrap.o
../src/VideoCaptureWrap.cc:190:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    Local<Object> im_to_return= Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/VideoCaptureWrap.cc:229:77: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im_to_return= Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                            ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/opencv/src/CamShift.o
  CXX(target) Release/obj.target/opencv/src/HighGUI.o
  CXX(target) Release/obj.target/opencv/src/FaceRecognizer.o
../src/FaceRecognizer.cc:11:19: error: no member named 'createEigenFaceRecognizer' in namespace 'cv::face'; did you mean 'EigenFaceRecognizer'?
  using cv::face::createEigenFaceRecognizer;
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                  EigenFaceRecognizer
/usr/local/Cellar/opencv/3.3.1/include/opencv2/face/facerec.hpp:54:20: note: 'EigenFaceRecognizer' declared here
class CV_EXPORTS_W EigenFaceRecognizer : public BasicFaceRecognizer
                   ^
../src/FaceRecognizer.cc:12:19: error: no member named 'createFisherFaceRecognizer' in namespace 'cv::face'; did you mean 'FisherFaceRecognizer'?
  using cv::face::createFisherFaceRecognizer;
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
                  FisherFaceRecognizer
/usr/local/Cellar/opencv/3.3.1/include/opencv2/face/facerec.hpp:89:20: note: 'FisherFaceRecognizer' declared here
class CV_EXPORTS_W FisherFaceRecognizer : public BasicFaceRecognizer
                   ^
../src/FaceRecognizer.cc:13:19: error: no member named 'createLBPHFaceRecognizer' in namespace 'cv::face'; did you mean 'LBPHFaceRecognizer'?
  using cv::face::createLBPHFaceRecognizer;
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
                  LBPHFaceRecognizer
/usr/local/Cellar/opencv/3.3.1/include/opencv2/face/facerec.hpp:126:20: note: 'LBPHFaceRecognizer' declared here
class CV_EXPORTS_W LBPHFaceRecognizer : public FaceRecognizer
                   ^
../src/FaceRecognizer.cc:71:39: error: no member named 'createLBPHFaceRecognizer' in namespace 'cv'
  cv::Ptr<cv::FaceRecognizer> f = cv::createLBPHFaceRecognizer(1, 8, 8, 8, 80.0);
                                  ~~~~^
../src/FaceRecognizer.cc:93:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> n = Nan::New(FaceRecognizerWrap::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/FaceRecognizer.cc:94:39: error: no member named 'createLBPHFaceRecognizer' in namespace 'cv'
  cv::Ptr<cv::FaceRecognizer> f = cv::createLBPHFaceRecognizer(radius,
                                  ~~~~^
../src/FaceRecognizer.cc:111:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> n = Nan::New(FaceRecognizerWrap::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/FaceRecognizer.cc:112:39: error: no member named 'createEigenFaceRecognizer' in namespace 'cv'
  cv::Ptr<cv::FaceRecognizer> f = cv::createEigenFaceRecognizer(components,
                                  ~~~~^
../src/FaceRecognizer.cc:129:79: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> n = Nan::New(FaceRecognizerWrap::constructor)->GetFunction()->NewInstance();
                                                                              ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/FaceRecognizer.cc:131:39: error: no member named 'createFisherFaceRecognizer' in namespace 'cv'
  cv::Ptr<cv::FaceRecognizer> f = cv::createFisherFaceRecognizer(components,
                                  ~~~~^
../src/FaceRecognizer.cc:391:14: error: no matching member function for call to 'load'
  self->rec->load(filename);
  ~~~~~~~~~~~^~~~
/usr/local/Cellar/opencv/3.3.1/include/opencv2/core.hpp:3134:44: note: candidate template ignored: couldn't infer template argument '_Tp'
    template<typename _Tp> static Ptr<_Tp> load(const String& filename, const String& objname=String())
                                           ^
../src/FaceRecognizer.cc:423:68: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> im = Nan::New(Matrix::constructor)->GetFunction()->NewInstance();
                                                                   ^
/Users/limi/.node-gyp/8.8.1/include/node/v8.h:3836:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/limi/.node-gyp/8.8.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
4 warnings and 8 errors generated.
make: *** [Release/obj.target/opencv/src/FaceRecognizer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Users/limi/.nvm/versions/node/v8.8.1/bin/node" "/Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64"
gyp ERR! cwd /Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/limi/.nvm/versions/node/v8.8.1/bin/node /Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 17.0.0
node-pre-gyp ERR! command "/Users/limi/.nvm/versions/node/v8.8.1/bin/node" "/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute '/Users/limi/.nvm/versions/node/v8.8.1/bin/node /Users/limi/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/limi/tbsCode/weixin-chrome-110/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64' (1)

```
</details>

**Comment by MRsJackYang** [comment]
did  you  reslove it
