### ISSUE TITLE
opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by amit034** [peterbraden/node-opencv#593]
im getting this error while trying to install opencv --python=2.7

```
> opencv@6.0.0 install C:\work\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-win32-x64.tar.g
z
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.2.0 (node-v48 ABI, unknown) (falling back to sourc
e compile with node-gyp)

C:\work\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\work\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\work\node_modules\opencv\build\ope
ncv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\opencv\build\opencv
\v6.0.0\Release\node-v48-win32-x64 --python=2.7 )  else (node "" configure --fallback-to-build --module=C:\work\node_modules\
opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\ope
ncv\build\opencv\v6.0.0\Release\node-v48-win32-x64 --python=2.7 )

C:\work\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\work\node_modules\opencv\build\opencv\
v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\opencv\build\opencv\v6.
0.0\Release\node-v48-win32-x64 )  else (node "" build --fallback-to-build --module=C:\work\node_modules\opencv\build\opencv\v
6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\opencv\build\opencv\v6.0
.0\Release\node-v48-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
..\src\Matrix.cc(321): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\work\node
_modules\opencv\build\opencv.vcxproj]
..\src\Matrix.cc(663): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\nod
e_modules\opencv\build\opencv.vcxproj]
..\src\Matrix.cc(701): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\nod
e_modules\opencv\build\opencv.vcxproj]
..\src\Matrix.cc(1264): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\no
de_modules\opencv\build\opencv.vcxproj]
..\src\Matrix.cc(2075): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\work\node_
modules\opencv\build\opencv.vcxproj]
..\src\OpenCV.cc(44): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\w
ork\node_modules\opencv\build\opencv.vcxproj]
c:\work\node_modules\opencv\node_modules\nan\nan_new.h(208): warning C4267: 'argument': conversion from 'size_t' to 'int', p
ossible loss of data (compiling source file ..\src\CascadeClassifierWrap.cc) [C:\work\node_modules\opencv\build\opencv.vcxpr
oj]
  ..\src\CascadeClassifierWrap.cc(86): note: see reference to function template instantiation 'v8::Local<v8::Array> Nan::New
  <v8::Array,unsigned __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
c:\work\node_modules\opencv\node_modules\nan\nan_new.h(208): warning C4267: 'argument': conversion from 'size_t' to 'int', p
ossible loss of data (compiling source file ..\src\Matrix.cc) [C:\work\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Matrix.cc(1523): note: see reference to function template instantiation 'v8::Local<v8::Array> Nan::New<v8::Array,un
  signed __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
..\src\Contours.cc(87): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\no
de_modules\opencv\build\opencv.vcxproj]
..\src\Contours.cc(307): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\n
ode_modules\opencv\build\opencv.vcxproj]
..\src\Contours.cc(309): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\n
ode_modules\opencv\build\opencv.vcxproj]
..\src\Contours.cc(320): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\work\n
ode_modules\opencv\build\opencv.vcxproj]
c:\work\node_modules\opencv\node_modules\nan\nan_new.h(208): warning C4267: 'argument': conversion from 'size_t' to 'int', p
ossible loss of data (compiling source file ..\src\Contours.cc) [C:\work\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Contours.cc(80): note: see reference to function template instantiation 'v8::Local<v8::Array> Nan::New<v8::Array,un
  signed __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
..\src\BackgroundSubtractor.cc(89): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss
 of data [C:\work\node_modules\opencv\build\opencv.vcxproj]
  Constants.cc
  Calib3D.cc
  ImgProc.cc
  Stereo.cc
..\src\Constants.cc(5): warning C4005: 'CONST': macro redefinition [C:\work\node_modules\opencv\build\opencv.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(153): note: see previous definition of 'CONST' (compili
  ng source file ..\src\Constants.cc)
c:\work\node_modules\opencv\node_modules\nan\nan_new.h(208): warning C4267: 'argument': conversion from 'size_t' to 'int', p
ossible loss of data (compiling source file ..\src\Calib3D.cc) [C:\work\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Calib3D.cc(144): note: see reference to function template instantiation 'v8::Local<v8::Array> Nan::New<v8::Array,un
  signed __int64>(A0)' being compiled
          with
          [
              A0=unsigned __int64
          ]
  LDAWrap.cc
  win_delay_load_hook.c
     Creating library C:\work\node_modules\opencv\build\Release\opencv.lib and object C:\work\node_modules\opencv\build\Rele
  ase\opencv.exp
  Generating code
  Finished generating code
  opencv.vcxproj -> C:\work\node_modules\opencv\build\Release\\opencv.node
  Copying C:\work\node_modules\opencv\build\Release\/opencv.node to C:/work/node_modules/opencv/build/opencv/v6.0.0/Release/
  node-v48-win32-x64\opencv.node
          1 file(s) copied.
  nativemat.cc
c:\users\amitr\downloads\opencv\opencv\build\include\opencv2\flann\any.h(48): error C2039: 'type_info': is not a member of '
std' [C:\work\node_modules\opencv\build\test_nativemat.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(15): note: see declaration of 'std'
c:\users\amitr\downloads\opencv\opencv\build\include\opencv2\flann\any.h(60): error C2039: 'type_info': is not a member of '
std' [C:\work\node_modules\opencv\build\test_nativemat.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(15): note: see declaration of 'std'
  c:\users\amitr\downloads\opencv\opencv\build\include\opencv2\flann\any.h(80): note: see reference to class template instan
  tiation 'cvflann::anyimpl::typed_base_any_policy<T>' being compiled
          with
          [
              T=cvflann::flann_centers_init_t
          ]
  c:\users\amitr\downloads\opencv\opencv\build\include\opencv2\flann\any.h(102): note: see reference to class template insta
  ntiation 'cvflann::anyimpl::big_any_policy<cvflann::flann_centers_init_t>' being compiled
c:\users\amitr\downloads\opencv\opencv\build\include\opencv2\flann\any.h(302): error C2039: 'type_info': is not a member of
'std' [C:\work\node_modules\opencv\build\test_nativemat.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(15): note: see declaration of 'std'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23
)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\
\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\work\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\no
de-v48-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\work\\node_modules\\opencv\\build\\opencv\\v6.0.0\\R
elease\\node-v48-win32-x64"
gyp ERR! cwd C:\work\node_modules\opencv
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\work\node_modules\opencv
\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\opencv\bu
ild\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\work\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compi
le.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\work\\node_modules\\opencv\\node_modules\\node-pre-gyp\\
bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\work\node_modules\opencv
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\work\node_modules\opencv\build\opencv\v6.0.0\Release\no
de-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\work\node_modules\opencv\build\opencv\v6.0.0\Release\node-
v48-win32-x64' (1)
work@1.0.0 C:\work
`-- open@0.0.5

npm WARN work@1.0.0 No description
npm WARN work@1.0.0 No repository field.
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.39
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "opencv" "--python=2.7"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\work\adtec_face_detection\npm-debug.log
```

my preset: 
Win: 10
NodeJs: 6.2.0
NPM: 3.8.9
OpenCV: 2.4.13.4
Visual Studio: 2015

**Comment by btsimonh** [comment]
may have similarities with: https://github.com/peterbraden/node-opencv/issues/591
as opencv.node has built correctly, only nativemat did not;  I still don't know if such a failed build produces a usable node-opencv, or if gyp rolls it back as a fail.  
However, if you have the opportunity to try the node versions mentioned there, it may be worthwhile.

for reference, my buildlog for VC14 with opencv3.3 (from zip) is here:
https://gist.github.com/btsimonh/b27b21e6a5d02c2a9f92ec76d60eb793

I have NOT used it in windows, but the build seems successful.

**Comment by btsimonh** [comment]
yes, it does run once i do:
set path=%path%;C:\DataNoBackup\ocv3.3.1\opencv\build\x64\vc14\bin
then running examples works in node-opencv.

**Comment by btsimonh** [comment]
@amit034 - were you successful?
closing now; re-open if you are still struggling
