### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by alaa069** [peterbraden/node-opencv#616]
Hello,
When I am trying to run my application after installing all package, I get this message

```
Error: dlopen(/Users/MKB.UPPERSKILLS/Downloads/Emotion_Detection-master/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node, 1): Library not loaded: /usr/local/opt/tesseract/lib/libtesseract.3.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_text.3.4.dylib
  Reason: image not found
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/MKB.UPPERSKILLS/Downloads/Emotion_Detection-master/node_modules/opencv/lib/bindings.js:4:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

macOS : high Sierra 10.13.1
Node version : 8.9.1
NPM version : 5.6.0
OpenCV version : 3.4.1_2

Thanks.

**Comment by MRsJackYang** [comment]
Did you slove it?
