### ISSUE TITLE
different release version of opencv.node

### ISSUE THREAD

**Issue by yw774** [peterbraden/node-opencv#618]
After install opencv@5.0.0, I had a folder named node-v46-linux-x64 but not node-v56-linux-x64.

```
> require("opencv")
Error: Cannot find module '....../...../node_modules/opencv/build/opencv/v5.0.0/Release/node-v59-linux-x64/opencv.node'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

nodejs v9.8.0
npm 5.6.0
opecv 3.4.1
ubuntu 16.4

**Comment by peterbraden** [comment]
try 6.2
