### ISSUE TITLE
Missing histogram bindings

### ISSUE THREAD

**Issue by NicolasRannou** [peterbraden/node-opencv#629]
Hi,

I try to run the `emd` example but somehow `histogram` is not defined:

```
/Users/nico/work/gitroot/ami/webGLTesting.js:92
    var firstImageHist64 = cv.histogram.calcHist(im1, channels, size, range, uniform);
                                        ^

TypeError: Cannot read property 'calcHist' of undefined
    at /Users/nico/work/gitroot/ami/webGLTesting.js:92:41
    at /Users/nico/work/gitroot/ami/webGLTesting.js:75:6
    at /Users/nico/work/gitroot/ami/webGLTesting.js:72:4
    at <anonymous>
```

**Comment by NicolasRannou** [comment]
The npm package is outdated - latest master works OK

**Comment by robin22d** [comment]
Hi @NicolasRannou, Im getting the same error how did you update to the latest package? I am running version "opencv": "^6.0.0"

**Comment by peterbraden** [comment]
try 6.2
