### ISSUE TITLE
Spent weeks trying to figure out install error to no avail

### ISSUE THREAD

**Issue by Nick-lab** [peterbraden/node-opencv#646]
Been trying to get this package to install for weeks now and didn't want to bother devs but i am at the end of my rope. have come from all other common errors that where fixed from other tickets like [#580](https://github.com/peterbraden/node-opencv/issues/580) and making sure Python Path is defined correctly now im having issues with MSBuild.exe and have tried to follow general fixes for this error mostly for node-gyp package but am not sure if this was necessary.

Output
```
node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
  Constants.cc
  Calib3D.cc
  ImgProc.cc
  Stereo.cc
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
  Constants.cc
  Calib3D.cc
  ImgProc.cc
  Stereo.cc
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\CascadeClassifierWrap.cc) [C:
\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
  LDAWrap.cc
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Matrix.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
  win_delay_load_hook.cc
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Users\Brian\Docu
ments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\OpenCV.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Contours.cc) [C:\Users\Brian\
Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Point.cc) [C:\Users\Brian\Doc
uments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\ImgProc.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\BackgroundSubtractor.cc) [C:\
Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\HighGUI.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Calib3D.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\CamShift.cc) [C:\Users\Brian\
Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\VideoCaptureWrap.cc) [C:\User
s\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\FaceRecognizer.cc) [C:\Users\
Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Features2d.cc) [C:\Users\Bria
n\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Users\Brian\Docu
ments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Contours.cc) [C:\Users\Brian\
Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Constants.cc) [C:\Users\Brian
\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Stereo.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
  LDAWrap.cc
  win_delay_load_hook.cc
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Constants.cc) [C:\Users\Brian
\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\FaceRecognizer.cc) [C:\Users\
Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Matrix.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Point.cc) [C:\Users\Brian\Doc
uments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\CamShift.cc) [C:\Users\Brian\
Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\CascadeClassifierWrap.cc) [C:
\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\HighGUI.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\ImgProc.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Stereo.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Features2d.cc) [C:\Users\Bria
n\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\OpenCV.cc) [C:\Users\Brian\Do
cuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\VideoCaptureWrap.cc) [C:\User
s\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\BackgroundSubtractor.cc) [C:\
Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\Calib3D.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\LDAWrap.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\users\brian\documents\apps\electron apps\axehouse\node_modules\opencv\src\opencv.h(19): fatal error C1083: Cannot open include file: 'opencv/cv.h': No such file or directory (compiling source file ..\src\LDAWrap.cc) [C:\Users\Brian\D
ocuments\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Brian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Brian\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Brian\\Documents\\apps\\Electron Apps\\AxeHouse\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v64-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Users\\Brian\\Documents\\apps\\Electron Apps\\AxeHouse\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v64-win32-x64"
gyp ERR! cwd C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Brian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv\v6.0.0\Release\node-v64-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\build\opencv\v6.0.0\Release\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Brian\\Documents\\apps\\Electron Apps\\AxeHouse\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
```

any help would be appreciated.

edit
```
node version: v10.15.0
python: 3.7.0 -> tried using 2.7.16 same error
```

*sigh* kinda figured I wouldn't get anything back.

**Comment by Nick-lab** [comment]
damn well over a week and nothing at all? not even any acknowledgement of the issue i'm having. . . knew this was going to be useless asking this here.

**Comment by jasonpolites** [comment]
Looks like the same as #642

Might be a simple fix (possibly S3 bucket permissions), but right now it seems like this module is completely broken/unusable

**Comment by peterbraden** [comment]
S3 was only ever a temporary cache for prebuilt binaries, but it was causing too much confusion so I removed it.

**Comment by Nick-lab** [comment]
still same error is there a version to install for this fix? eg `npm install --save opencv@6.2.0` ?

**Comment by peterbraden** [comment]
6.2 should be fine

**Comment by Nick-lab** [comment]
still same issue
````
C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Users\Brian\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Brian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  VideoWriterWrap.cc
  CamShift.cc
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
  Constants.cc
  Calib3D.cc
  ImgProc.cc
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Point.cc) [C:\Users\Brian\Documents\apps\Electron Apps\Ax
eHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Users\Brian\Documents\apps\Electron Apps\Axe
House\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\VideoCaptureWrap.cc) [C:\Users\Brian\Documents\apps\Elect
ron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Constants.cc) [C:\Users\Brian\Documents\apps\Electron App
s\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\ImgProc.cc) [C:\Users\Brian\Documents\apps\Electron Apps\
AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\FaceRecognizer.cc) [C:\Users\Brian\Documents\apps\Electro
n Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Contours.cc) [C:\Users\Brian\Documents\apps\Electron Apps
\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Matrix.cc) [C:\Users\Brian\Documents\apps\Electron Apps\A
xeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\VideoWriterWrap.cc) [C:\Users\Brian\Documents\apps\Electr
on Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\OpenCV.cc) [C:\Users\Brian\Documents\apps\Electron Apps\A
xeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\HighGUI.cc) [C:\Users\Brian\Documents\apps\Electron Apps\
AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Calib3D.cc) [C:\Users\Brian\Documents\apps\Electron Apps\
AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\CamShift.cc) [C:\Users\Brian\Documents\apps\Electron Apps
\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\CascadeClassifierWrap.cc) [C:\Users\Brian\Documents\apps\
Electron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\BackgroundSubtractor.cc) [C:\Users\Brian\Documents\apps\E
lectron Apps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Features2d.cc) [C:\Users\Brian\Documents\apps\Electron Ap
ps\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
  Stereo.cc
  LDAWrap.cc
  Histogram.cc
  win_delay_load_hook.cc
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Stereo.cc) [C:\Users\Brian\Documents\apps\Electron Apps\A
xeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\Histogram.cc) [C:\Users\Brian\Documents\apps\Electron App
s\AxeHouse\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\src\LDAWrap.cc) [C:\Users\Brian\Documents\apps\Electron Apps\
AxeHouse\node_modules\opencv\build\opencv.vcxproj]
  nativemat.cc
  win_delay_load_hook.cc
c:\opencv\build\include\opencv2\photo\photo.hpp(49): fatal error C1083: Cannot open include file: 'opencv2/photo/photo_
c.h': No such file or directory (compiling source file ..\test\nativemat.cc) [C:\Users\Brian\Documents\apps\Electron Ap
ps\AxeHouse\node_modules\opencv\build\test_nativemat.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Brian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Brian\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Brian\Documents\apps\Electron Apps\AxeHouse\node_modules\opencv
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN @angular/animations@7.2.0 requires a peer of @angular/core@7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Brian\AppData\Roaming\npm-cache\_logs\2019-03-22T13_01_03_787Z-debug.log
````

**Comment by jasonpolites** [comment]
I don't think that's the same issue. That looks like a path problem where node-opencv can't find you're local install of opencv

**Comment by Nick-lab** [comment]
that's weird i have all the paths correct
```
C:\Users\Brian\Documents\apps\tane>echo %OPENCV_DIR%
C:\OpenCV\build\x64\vc14

C:\Users\Brian\Documents\apps\tane>echo %OPENCV_INCLUDE_DIR%
C:\OpenCV\build\include

C:\Users\Brian\Documents\apps\tane>echo %OPENCV_LIB_DIR%
C:\OpenCV\build\x64\vc14\lib
```

**Comment by jasonpolites** [comment]
Yeah not sure, just saying that this:
```
Cannot open include file: 'opencv2/photo/photo_c.h': No such file or directory
```
Doesn't look the same as the original S3 issue.

**Comment by Nick-lab** [comment]
okay well ill leave this issue closed then. I just don't want to bother anybody else or open a new issue. Thanks for all the help you two have given me I really do appreciate it.

**Comment by Nick-lab** [comment]
if anybody else is having this same issue with node-opencv go to [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs) repository much better installation let it generate and install for you instead of trying to figure out what is breaking this one.

**Comment by stoefln** [comment]
@Nick-lab did you get opencv4nodejs running? I mean did you manage to bundle it? I am trying since weeks and can't get it working...
