### ISSUE TITLE
module import Error

### ISSUE THREAD

**Issue by qultelyTao** [peterbraden/node-opencv#662]
hi:
    I copy the project code and report an error when running the example
   eg:
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\node-opencv-master\build\Release\opencv.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\node-opencv-master\lib\bindings.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by peterbraden** [comment]
Is this an issue with latest version?

**Comment by git-chenjiqing** [comment]
我也遇到了此问题，请问有解决吗?
