### ISSUE TITLE
opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory

### ISSUE THREAD

**Issue by tiny-tinker** [peterbraden/node-opencv#95]
Hello people!
    I am hoping someone can point me in the right direction.... I am getting this error when trying to install this opencv package on my Win 7 x64 box... I suspect something is funky with opencv.vcxproj file, but I'm not familiar with programming on windows... 
Thanks!!

C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog>npm install opencv
npm http GET https://registry.npmjs.org/opencv
npm http 304 https://registry.npmjs.org/opencv

> opencv@0.3.1 preinstall C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv
> node-gyp clean rebuild

C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Contours.cc
  Point.cc
  CascadeClassifierWrap.cc
  Matrix.cc
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv\build\opencv.vcxproj]
  VideoCaptureWrap.cc
  init.cc
  OpenCV.cc
  FaceRecognizer.cc
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
  CamShift.cc
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
  HighGUI.cc
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
c:\users\jo\dropbox\tinkering\nodejs\facerecog\node_modules\opencv\src\OpenCV.h(9): fatal error C1083: Cannot open include file: 'cv.h': No such file or directory [C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "clean" "rebuild"
gyp ERR! cwd C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\node_modules\opencv
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok
npm ERR! opencv@0.3.1 preinstall: `node-gyp clean rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@0.3.1 preinstall script.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "opencv"
npm ERR! cwd C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog\npm-debug.log
npm ERR! not ok code 0

C:\Users\jo\Dropbox\Tinkering\NodeJS\FaceRecog>

**Comment by gongfan99** [comment]
If you are installing this package in windows, you need to be carefully with the opencv.pc file.

It should NOT be:
Cflags: -I${includedir}/

It should be:
Cflags: ${includedir}/

The problem is that the "binding.gyp" file uses "--cflags" for 'include_dirs', which I think is not a very nice-looking way.

**Comment by wasimziya** [comment]
pkg-config uses base directory as a default prefix on windows.
add one more argument --dont-define-prefix with --cflags to override default

**Comment by csjavadev** [comment]
Just had the exact same error, with the `cv.h` file cannot open in visual studio 2012. Tried reinstalling opencv completely, reset environment variables for the compiler, edited the linker include and lib directories in debug and active/release properties to the path for the opencv/build/x64/lib and opencv/build/x64/include neither worked. also tried another suggestion to copy rc.exe and rcDLL.dll from MicrosoftSDKs/bin/vc/ to /Program Files(x86)/Microsoft Visual Studio 11.0/ VC/bin/ and that did not work either. Did anyone ever find a solution to this error?

**Comment by nomadic-squirrel** [comment]
I did not. I gave up trying to compile on windows which is not my strong point.
